# -*- coding: utf-8 -*-
"""Phase 1 of DMML MINI Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15jC5AUbBo7VN8oqh9FbBtcHvIvXKMnIL
"""

_# ============================================
# FULL DATASET: DOMAIN-LEVEL CREATION
# (Using SAME variable names for pipeline compatibility)
# ============================================

import kagglehub
import os
import pandas as pd
from urllib.parse import urlparse

# -------------------------------
# Step A: Download Dataset
# -------------------------------
path = kagglehub.dataset_download("sid321axn/malicious-urls-dataset")
print("Dataset folder path:", path)

files = os.listdir(path)
print("Files inside dataset folder:", files)

csv_path = os.path.join(path, files[0])
df = pd.read_csv(csv_path)

print("\nOriginal dataset shape:", df.shape)
print("Original class distribution:")
print(df['type'].value_counts())


# -------------------------------
# Step B: Extract Domain Safely
# -------------------------------

def extract_domain_safe(url):
    try:
        parsed = urlparse(url)

        if not parsed.netloc:
            parsed = urlparse("http://" + url)

        domain = parsed.netloc

        if domain.startswith("www."):
            domain = domain[4:]

        return domain.lower()

    except Exception:
        return None


df['domain'] = df['url'].apply(extract_domain_safe)

print("\nSample after domain extraction:")
print(df[['url','domain']].head())


# -------------------------------
# Step C: Remove Invalid Domains
# -------------------------------
df = df.dropna(subset=['domain'])
print("\nAfter removing invalid domains:")
print("Dataset shape:", df.shape)


# -------------------------------
# Step D: Remove Duplicate Domains
# -------------------------------
df = df.drop_duplicates(subset='domain')
print("\nAfter removing duplicate domains:")
print("Dataset shape:", df.shape)


# -------------------------------
# Step E: Convert Multi-class to Binary
# -------------------------------

def convert_label(x):
    if x == 'benign':
        return 0
    else:
        return 1

df['label'] = df['type'].apply(convert_label)

print("\nBinary class distribution:")
print(df['label'].value_counts())


# -------------------------------
# Step F: Use SAME Variable Name (balanced_df)
# -------------------------------

# IMPORTANT: We keep variable name as balanced_df
# but now it contains FULL dataset (no sampling)

balanced_df = df.copy().reset_index(drop=True)

print("\nUsing FULL dataset:")
print(balanced_df['label'].value_counts())
print("Dataset shape:", balanced_df.shape)


# -------------------------------
# Step G: Keep Only Required Columns
# -------------------------------

final_df = balanced_df[['domain','label']].copy()

print("\nFinal Dataset Preview:")
print(final_df.head())
print("Final dataset shape:", final_df.shape)


# -------------------------------
# Step H: Save Dataset
# -------------------------------

final_df.to_csv("full_domain_dataset.csv", index=False)

print("\nFull dataset saved successfully!")

# ============================================
# PART 2: FEATURE ENGINEERING (FIXED VERSION)
# ============================================

import numpy as np
import re
import math

# IMPORTANT FIX → use .copy() to avoid SettingWithCopyWarning
final_df = balanced_df[['domain','label']].copy()

# -------------------------------
# Lexical Features
# -------------------------------

# 1. Domain Length
final_df.loc[:, 'domain_length'] = final_df['domain'].apply(len)

# 2. Dot Count (Subdomain levels)
final_df.loc[:, 'dot_count'] = final_df['domain'].apply(lambda x: x.count('.'))

# 3. Hyphen Count
final_df.loc[:, 'hyphen_count'] = final_df['domain'].apply(lambda x: x.count('-'))

# 4. Digit Count
final_df.loc[:, 'digit_count'] = final_df['domain'].apply(lambda x: sum(c.isdigit() for c in x))

# 5. Digit Ratio
final_df.loc[:, 'digit_ratio'] = final_df['digit_count'] / final_df['domain_length']

# 6. Special Character Count
final_df.loc[:, 'special_char_count'] = final_df['domain'].apply(
    lambda x: len(re.findall(r'[^a-zA-Z0-9.-]', x))
)

# 7. Vowel Count
final_df.loc[:, 'vowel_count'] = final_df['domain'].apply(
    lambda x: sum(c in 'aeiou' for c in x)
)

# 8. Vowel Ratio
final_df.loc[:, 'vowel_ratio'] = final_df['vowel_count'] / final_df['domain_length']

# 9. Consonant Count
final_df.loc[:, 'consonant_count'] = final_df['domain'].apply(
    lambda x: sum(c.isalpha() and c not in 'aeiou' for c in x)
)

# 10. Shannon Entropy
def shannon_entropy(domain):
    prob = [float(domain.count(c)) / len(domain) for c in dict.fromkeys(list(domain))]
    entropy = - sum([p * math.log2(p) for p in prob])
    return entropy

final_df.loc[:, 'entropy'] = final_df['domain'].apply(shannon_entropy)
# IMPORTANT: use original df with full URLs

balanced_df = balanced_df.copy()

# 1. URL Length
balanced_df['url_length'] = balanced_df['url'].apply(len)

# 2. Path Length
balanced_df['path_length'] = balanced_df['url'].apply(
    lambda x: len(urlparse(x).path)
)

# 3. Query Length
balanced_df['query_length'] = balanced_df['url'].apply(
    lambda x: len(urlparse(x).query)
)

# 4. URL Depth (Number of '/')
balanced_df['url_depth'] = balanced_df['url'].apply(
    lambda x: urlparse(x).path.count('/')
)

# 5. Number of Parameters
balanced_df['param_count'] = balanced_df['url'].apply(
    lambda x: urlparse(x).query.count('&') + 1 if urlparse(x).query else 0
)

# 6. Suspicious File Extension
suspicious_ext = ['.exe','.zip','.rar','.js','.php','.scr','.bat']

def suspicious_extension(url):
    for ext in suspicious_ext:
        if url.lower().endswith(ext):
            return 1
    return 0

balanced_df['suspicious_extension'] = balanced_df['url'].apply(suspicious_extension)

# 7. Encoded Characters (%)
balanced_df['encoded_char_count'] = balanced_df['url'].apply(
    lambda x: x.count('%')
)

# 8. Multiple Subdomains
balanced_df['multiple_subdomains'] = balanced_df['domain'].apply(
    lambda x: 1 if x.count('.') > 2 else 0
)


# -------------------------------
# CTI-Inspired Features
# -------------------------------

# 11. Suspicious TLD Flag
suspicious_tlds = ['xyz','tk','top','club','work','gq','cf','ml','ga']

def suspicious_tld(domain):
    tld = domain.split('.')[-1]
    return 1 if tld in suspicious_tlds else 0

final_df.loc[:, 'suspicious_tld_flag'] = final_df['domain'].apply(suspicious_tld)

# 12. Suspicious Keyword Flag
keywords = ['login','verify','secure','account','update','bank','paypal','signin','confirm']

def suspicious_keyword(domain):
    for word in keywords:
        if word in domain:
            return 1
    return 0

final_df.loc[:, 'suspicious_keyword_flag'] = final_df['domain'].apply(suspicious_keyword)

# 13. Length Anomaly (>25 characters)
final_df.loc[:, 'length_anomaly'] = final_df['domain_length'].apply(
    lambda x: 1 if x > 25 else 0
)

# 14. Contains IP Address
def contains_ip(domain):
    pattern = r'\d+\.\d+\.\d+\.\d+'
    return 1 if re.search(pattern, domain) else 0

final_df.loc[:, 'contains_ip'] = final_df['domain'].apply(contains_ip)

# 15. Risk Score (Combined Heuristic CTI Score)
final_df.loc[:, 'risk_score'] = (
    final_df['suspicious_tld_flag'] +
    final_df['suspicious_keyword_flag'] +
    final_df['length_anomaly'] +
    final_df['contains_ip']
)

print("Feature Engineering Completed Successfully ✅")
print("Final dataset shape:", final_df.shape)
print("\nFinal dataset preview:")
print(final_df.head())

# ============================================
# PART 2: FEATURE ENGINEERING (FIXED VERSION)
# ============================================

import numpy as np
import re
import math
from urllib.parse import urlparse
from collections import Counter

# IMPORTANT: Keep same variable names
final_df = balanced_df[['domain','label']].copy()

# -------------------------------
# Lexical Features
# -------------------------------

final_df['domain_length'] = final_df['domain'].apply(len)

final_df['dot_count'] = final_df['domain'].apply(lambda x: x.count('.'))

final_df['hyphen_count'] = final_df['domain'].apply(lambda x: x.count('-'))

final_df['digit_count'] = final_df['domain'].apply(lambda x: sum(c.isdigit() for c in x))

final_df['digit_ratio'] = final_df['digit_count'] / final_df['domain_length']

final_df['special_char_count'] = final_df['domain'].apply(
    lambda x: len(re.findall(r'[^a-zA-Z0-9.-]', x))
)

final_df['vowel_count'] = final_df['domain'].apply(
    lambda x: sum(c in 'aeiou' for c in x)
)

final_df['vowel_ratio'] = final_df['vowel_count'] / final_df['domain_length']

final_df['consonant_count'] = final_df['domain'].apply(
    lambda x: sum(c.isalpha() and c not in 'aeiou' for c in x)
)

# RESTORED ENTROPY
def shannon_entropy(domain):
    prob = [float(domain.count(c)) / len(domain) for c in set(domain)]
    return -sum([p * math.log2(p) for p in prob])

final_df['entropy'] = final_df['domain'].apply(shannon_entropy)

# -------------------------------
# URL-based features (use balanced_df)
# -------------------------------

balanced_df['url_length'] = balanced_df['url'].apply(len)

balanced_df['path_length'] = balanced_df['url'].apply(
    lambda x: len(urlparse(x).path)
)

balanced_df['query_length'] = balanced_df['url'].apply(
    lambda x: len(urlparse(x).query)
)

balanced_df['url_depth'] = balanced_df['url'].apply(
    lambda x: urlparse(x).path.count('/')
)

balanced_df['param_count'] = balanced_df['url'].apply(
    lambda x: urlparse(x).query.count('&') + 1 if urlparse(x).query else 0
)

suspicious_ext = ['.exe','.zip','.rar','.js','.php','.scr','.bat']

balanced_df['suspicious_extension'] = balanced_df['url'].apply(
    lambda x: 1 if any(x.lower().endswith(ext) for ext in suspicious_ext) else 0
)

balanced_df['encoded_char_count'] = balanced_df['url'].apply(
    lambda x: x.count('%')
)

# NEW FEATURE: has_https
balanced_df['has_https'] = balanced_df['url'].apply(
    lambda x: 1 if x.startswith("https") else 0
)

# Merge URL features into final_df
url_features = [
    'url_length','path_length','query_length','url_depth',
    'param_count','suspicious_extension','encoded_char_count','has_https'
]

for col in url_features:
    final_df[col] = balanced_df[col]

# -------------------------------
# CTI Features
# -------------------------------

suspicious_tlds = ['xyz','tk','top','club','work','gq','cf','ml','ga']

final_df['suspicious_tld_flag'] = final_df['domain'].apply(
    lambda x: 1 if x.split('.')[-1] in suspicious_tlds else 0
)

keywords = ['login','verify','secure','account','update','bank','paypal','signin','confirm']

final_df['suspicious_keyword_flag'] = balanced_df['url'].apply(
    lambda x: 1 if any(word in x.lower() for word in keywords) else 0
)

final_df['length_anomaly'] = final_df['domain_length'].apply(
    lambda x: 1 if x > 25 else 0
)

final_df['contains_ip'] = final_df['domain'].apply(
    lambda x: 1 if re.search(r'\d+\.\d+\.\d+\.\d+', x) else 0
)

final_df['risk_score'] = (
    final_df['suspicious_tld_flag'] +
    final_df['suspicious_keyword_flag'] +
    final_df['length_anomaly'] +
    final_df['contains_ip']
)

# NEW FEATURE: tld_length
final_df['tld_length'] = final_df['domain'].apply(
    lambda x: len(x.split('.')[-1])
)

# -------------------------------
# Sequence Features
# -------------------------------

def longest_consonant_seq(domain):
    max_seq = current = 0
    for c in domain:
        if c.isalpha() and c not in 'aeiou':
            current += 1
            max_seq = max(max_seq, current)
        else:
            current = 0
    return max_seq

final_df['longest_consonant_seq'] = final_df['domain'].apply(longest_consonant_seq)

def longest_digit_seq(domain):
    max_seq = current = 0
    for c in domain:
        if c.isdigit():
            current += 1
            max_seq = max(max_seq, current)
        else:
            current = 0
    return max_seq

final_df['longest_digit_seq'] = final_df['domain'].apply(longest_digit_seq)

final_df['subdomain_depth'] = final_df['domain'].apply(
    lambda x: max(len(x.split('.')) - 2, 0)
)

# -------------------------------
# Bigram Randomness (Fixed smoothing)
# -------------------------------

def generate_bigrams(domain):
    return [domain[i:i+2] for i in range(len(domain)-1)]

all_bigrams = []
for d in final_df['domain']:
    all_bigrams.extend(generate_bigrams(d))

bigram_counts = Counter(all_bigrams)
total_bigrams = sum(bigram_counts.values())

def bigram_score(domain):
    bigrams = generate_bigrams(domain)
    score = 0
    for bg in bigrams:
        freq = bigram_counts.get(bg, 0.5) / total_bigrams
        score += -math.log2(freq)
    return score / len(bigrams) if bigrams else 0

final_df['bigram_randomness'] = final_df['domain'].apply(bigram_score)

print("Advanced Feature Engineering Completed 🚀")
print("Dataset shape:", final_df.shape)

# ============================================
# PART 3: EDA & FEATURE CORRELATION ANALYSIS
# ============================================

import matplotlib.pyplot as plt
import seaborn as sns

# --------------------------------
# 1. Class Distribution
# --------------------------------
plt.figure(figsize=(6,4))
sns.countplot(x='label', data=final_df)
plt.title("Class Distribution (0 = Benign, 1 = Malicious)")
plt.show()


# --------------------------------
# 2. Feature Distribution (Example)
# --------------------------------

plt.figure(figsize=(8,5))
sns.histplot(data=final_df, x='domain_length', hue='label', bins=40, kde=True)
plt.title("Domain Length Distribution by Class")
plt.show()


plt.figure(figsize=(8,5))
sns.histplot(data=final_df, x='entropy', hue='label', bins=40, kde=True)
plt.title("Entropy Distribution by Class")
plt.show()


# --------------------------------
# 3. Correlation Heatmap
# --------------------------------

# Drop non-numeric column
corr_df = final_df.drop(columns=['domain'])

plt.figure(figsize=(14,10))
sns.heatmap(corr_df.corr(), annot=False, cmap='coolwarm', center=0)
plt.title("Feature Correlation Heatmap")
plt.show()


# --------------------------------
# 4. Top Correlated Features with Label
# --------------------------------

label_corr = corr_df.corr()['label'].sort_values(ascending=False)

print("\nCorrelation with Label:")
print(label_corr)

# ============================================
# SAVE FINAL DATASET
# ============================================

# Save full dataset (with domain column)
final_df.to_csv("malicious_domain_features.csv", index=False)

# Save ML-ready dataset (drop domain column)
ml_ready_df = final_df.drop(columns=['domain']).copy()
ml_ready_df.to_csv("ml_ready_features.csv", index=False)

print("Datasets saved successfully ✅")
print("Full dataset shape:", final_df.shape)
print("ML-ready dataset shape:", ml_ready_df.shape)

# ============================================
# TRAIN-TEST SPLIT (70% TRAIN / 30% TEST)
# ============================================

from sklearn.model_selection import train_test_split
import pandas as pd # Ensure pandas is imported if not already

# Load ML-ready dataset (optional if restarting notebook)
ml_ready_df = pd.read_csv("ml_ready_features.csv")

# Separate features and target
X = ml_ready_df.drop(columns=['label'])
y = ml_ready_df['label']

# Store feature names as a global list for consistent feature engineering later
global feature_names
feature_names = X.columns.tolist()

print("Feature matrix shape:", X.shape)
print("Target vector shape:", y.shape)

# Train-test split (Stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("\nTrain shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTrain label distribution:")
print(y_train.value_counts())

print("\nTest label distribution:")
print(y_test.value_counts())

# ============================================
# SAVE ALL DATASETS INTO:
# MyDrive/DMML_MINI_PROJECT/dataset
# ============================================
from google.colab import drive
drive.mount('/content/drive')
import os
import pandas as pd

# Define main folder path
base_folder = "/content/drive/MyDrive/DMML_MINI_PROJECT/Dataset1"

# Create folder if it doesn't exist
os.makedirs(base_folder, exist_ok=True)

# -----------------------------
# Save Full Dataset (with domain column)
# -----------------------------
final_df.to_csv(
    os.path.join(base_folder, "malicious_domain_full.csv"),
    index=False
)

# -----------------------------
# Save ML-ready Dataset (without domain)
# -----------------------------
ml_ready_df = final_df.drop(columns=['domain']).copy()
ml_ready_df.to_csv(
    os.path.join(base_folder, "malicious_domain_ml_ready.csv"),
    index=False
)

# -----------------------------
# Save Train Dataset
# -----------------------------
train_df = X_train.copy()
train_df['label'] = y_train  # Removed .values for direct Series assignment
train_df.to_csv(
    os.path.join(base_folder, "train_dataset.csv"),
    index=False
)

# -----------------------------
# Save Test Dataset
# -----------------------------
test_df = X_test.copy()
test_df['label'] = y_test  # Removed .values for direct Series assignment
test_df.to_csv(
    os.path.join(base_folder, "test_dataset.csv"),
    index=False
)

print("All datasets saved successfully inside DMML_MINI_PROJECT/Dataset ✅")

"""**TRAINING RANDOM FOREST**"""

# ============================================
# STEP 0: MOUNT GOOGLE DRIVE
# ============================================

from google.colab import drive
drive.mount('/content/drive')


# ============================================
# STEP 1: IMPORTS
# ============================================

import os
import numpy as np
import pandas as pd
import joblib

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score


# ============================================
# STEP 2: PATH SETUP
# ============================================

save_path = "/content/drive/MyDrive/DMML_PROJECT"
os.makedirs(save_path, exist_ok=True)

model_path = os.path.join(save_path, "rf_model.pkl")


# ============================================
# STEP 3: CLEAN DATA
# ============================================

X_train = np.nan_to_num(X_train, nan=0.0, posinf=0.0, neginf=0.0)
X_test = np.nan_to_num(X_test, nan=0.0, posinf=0.0, neginf=0.0)


# ============================================
# STEP 4: LOAD OR TRAIN MODEL
# ============================================

if os.path.exists(model_path):
    print("🚀 Attempting to load saved Random Forest model...")
    try:
        rf = joblib.load(model_path)
        # Check if the loaded model is actually fitted
        if not hasattr(rf, 'estimators_') or not rf.estimators_:
            print("⚠️ Loaded model is not fitted or seems corrupted. Forcing retraining...")
            # Fallback to training
            print("🔥 Training Random Forest model...")
            rf = RandomForestClassifier(
                n_estimators=500,
                max_depth=20,
                min_samples_split=5,
                min_samples_leaf=2,
                random_state=42,
                n_jobs=-1
            )
            rf.fit(X_train, y_train)
            # Save the newly trained model
            joblib.dump(rf, model_path)
            print("✅ Newly trained model saved at:", model_path)
        else:
            print("✅ Random Forest model loaded successfully.")
    except Exception as e:
        print(f"❌ Error loading model: {e}. Forcing retraining...")
        # Fallback to training if loading fails
        print("🔥 Training Random Forest model...")
        rf = RandomForestClassifier(
            n_estimators=500,
            max_depth=20,
            min_samples_split=5,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=-1
        )
        rf.fit(X_train, y_train)
        # Save the newly trained model
        joblib.dump(rf, model_path)
        print("✅ Newly trained model saved at:", model_path)
elif os.path.exists("/content/drive/MyDrive/DMML_PROJECT/rf_model.pkl"):
    # Added this block to load the model from the expected path if it exists
    # but the previous check failed for some reason
    print("🚀 Attempting to load saved Random Forest model from DMML_PROJECT folder...")
    try:
        rf = joblib.load("/content/drive/MyDrive/DMML_PROJECT/rf_model.pkl")
        print("✅ Random Forest model loaded successfully.")
    except Exception as e:
        print(f"❌ Error loading model from specified path: {e}. Forcing retraining...")
        print("🔥 Training Random Forest model...")
        rf = RandomForestClassifier(
            n_estimators=500,
            max_depth=20,
            min_samples_split=5,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=-1
        )
        rf.fit(X_train, y_train)
        joblib.dump(rf, model_path)
        print("✅ Newly trained model saved at:", model_path)
else:
    print("🔥 Training Random Forest model (model file not found)...")
    rf = RandomForestClassifier(
        n_estimators=500,
        max_depth=20,
        min_samples_split=5,
        min_samples_leaf=2,
        random_state=42,
        n_jobs=-1
    )
    rf.fit(X_train, y_train)
    # Save model
    joblib.dump(rf, model_path)
    print("✅ Model saved at:", model_path)


# ============================================
# STEP 5: PREDICTIONS
# ============================================

y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]


# ============================================
# STEP 6: EVALUATION
# ============================================

print("\n===== RANDOM FOREST RESULTS =====")

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


# ============================================
# STEP 7: FEATURE IMPORTANCE
# ============================================

feature_names = X_train.columns if isinstance(X_train, pd.DataFrame) else [f"f{i}" for i in range(X_test.shape[1])]

importance = pd.Series(rf.feature_importances_, index=feature_names)
importance = importance.sort_values(ascending=False)

print("\nTop 15 Features:\n")
print(importance.head(15))


# ============================================
# STEP 8: PLOT FEATURE IMPORTANCE
# ============================================

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
importance.head(15).plot(kind='barh')
plt.gca().invert_yaxis()
plt.title("Top 15 Feature Importances (Random Forest)")
plt.xlabel("Importance Score")
plt.show()

"""**XGBOOST**"""

# ============================================
# IMPORTS
# ============================================

import numpy as np
import joblib
import os
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix


# ============================================
# HANDLE CLASS IMBALANCE
# ============================================

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale_pos_weight = neg / pos

print("scale_pos_weight:", scale_pos_weight)


# ============================================
# BUILD OPTIMIZED XGBOOST
# ============================================

xgb_model = XGBClassifier(
    n_estimators=800,              # more trees
    learning_rate=0.05,            # stable learning
    max_depth=6,                   # balanced complexity
    min_child_weight=3,            # prevents overfitting
    subsample=0.8,                 # row sampling
    colsample_bytree=0.8,          # feature sampling
    gamma=0.1,                     # split regularization
    reg_alpha=0.1,                 # L1 regularization
    reg_lambda=1.5,                # L2 regularization
    scale_pos_weight=scale_pos_weight,  # imbalance fix
    random_state=42,
    eval_metric='auc',
    tree_method='hist',            # faster
    n_jobs=-1
)


# ============================================
# TRAIN WITH EARLY STOPPING
# ============================================

xgb_model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    verbose=100
)


# ============================================
# PREDICTIONS
# ============================================

y_prob = xgb_model.predict_proba(X_test)[:, 1]


# ============================================
# 🔥 THRESHOLD TUNING (F1 OPTIMIZED)
# ============================================

from sklearn.metrics import f1_score

best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.4, 0.7, 0.01):
    y_pred_temp = (y_prob >= t).astype(int)
    f1 = f1_score(y_test, y_pred_temp)

    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print("\n🔥 Best Threshold:", best_thresh)
print("🔥 Best F1:", best_f1)


# ============================================
# FINAL EVALUATION
# ============================================

y_pred = (y_prob >= best_thresh).astype(int)

print("\n===== FINAL XGBOOST RESULTS =====")

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))


# ============================================
# SAVE MODEL
# ============================================

save_path = "/content/drive/MyDrive/DMML_PROJECT"
os.makedirs(save_path, exist_ok=True)
joblib.dump(xgb_model, os.path.join(save_path, "best_xgb_model.pkl"))

print("\nXGBoost model saved ✅")

!pip install catboost

# ============================================
# IMPORTS
# ============================================

import os
import joblib
import numpy as np

from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

# ============================================
# PATH SETUP
# ============================================

save_path = "/content/drive/MyDrive/DMML_PROJECT"
os.makedirs(save_path, exist_ok=True)

model_path = f"{save_path}/cat_model_final.cbm" # Changed extension to .cbm


# ============================================
# COMPUTE CLASS IMBALANCE
# ============================================

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale_pos_weight = neg / pos

print("Scale_pos_weight:", scale_pos_weight)


# ============================================
# LOAD OR TRAIN MODEL
# ============================================

cat_model = None
model_is_valid = False # Flag to track if loaded model is valid for prediction

if os.path.exists(model_path):
    print("Attempting to load saved CatBoost model 🚀")
    try:
        cat_model = CatBoostClassifier(verbose=False)
        cat_model.load_model(model_path)

        # Perform a quick compatibility check by predicting on a small subset
        # Ensure X_test is cleaned first as it's used directly in predict_proba later
        _X_test_clean = np.nan_to_num(X_test.copy(), nan=0.0, posinf=0.0, neginf=0.0)
        cat_model.predict_proba(_X_test_clean[:1]) # Predict on first sample to check compatibility

        print("✅ CatBoost model loaded and validated successfully.")
        model_is_valid = True
    except Exception as e:
        print(f"❌ Error loading or validating CatBoost model: {e}")
        print("    This usually means the saved model is incompatible with the current feature set.")
        print("    Deleting the old model file to force retraining.")
        if os.path.exists(model_path):
            os.remove(model_path)
            print(f"🗑️ Removed incompatible model file: {model_path}")
        cat_model = None # Ensure cat_model is None to trigger retraining

if not model_is_valid: # This block will run if model was not loaded successfully or failed validation
    print("Training optimized CatBoost model 🔥")

    cat_model = CatBoostClassifier(
        iterations=500,
        learning_rate=0.05,
        depth=6,
        l2_leaf_reg=3,

        # 🔥 IMPORTANT
        scale_pos_weight=scale_pos_weight,

        subsample=0.8,
        colsample_bylevel=0.8,

        loss_function='Logloss',
        eval_metric='AUC',

        random_seed=42,
        verbose=100
    )

    # Ensure X_train is cleaned before training
    _X_train_clean = np.nan_to_num(X_train.copy(), nan=0.0, posinf=0.0, neginf=0.0)
    cat_model.fit(_X_train_clean, y_train)

    # SAVE MODEL
    cat_model.save_model(model_path) # Changed to native save_model method
    print("CatBoost model saved ✅")


# ============================================
# PREDICTION
# ============================================

# Ensure X_test is cleaned before final prediction
_X_test_clean = np.nan_to_num(X_test.copy(), nan=0.0, posinf=0.0, neginf=0.0)
y_prob = cat_model.predict_proba(_X_test_clean)[:, 1]


# ============================================
# 🔥 BALANCED THRESHOLD TUNING (F1)
# ============================================

from sklearn.metrics import f1_score

best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.3, 0.7, 0.01):
    y_pred_temp = (y_prob >= t).astype(int)
    f1 = f1_score(y_test, y_pred_temp)

    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print("\n🔥 Best Threshold:", best_thresh)
print("🔥 Best F1 Score:", best_f1)


# ============================================
# FINAL RESULTS
# ============================================

y_pred = (y_prob >= best_thresh).astype(int)

print("\n===== FINAL CATBOOST RESULTS =====")

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

"""MLP"""

# ============================================
# STEP 0: MOUNT GOOGLE DRIVE
# ============================================

from google.colab import drive
drive.mount('/content/drive')


# ============================================
# STEP 1: IMPORTS
# ============================================

import os
import numpy as np
import pandas as pd
import joblib

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score, confusion_matrix
from sklearn.utils import class_weight

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.regularizers import l2
from tensorflow.keras.metrics import AUC # Added AUC metric


# ============================================
# STEP 2: PATH SETUP
# ============================================

save_path = "/content/drive/MyDrive/DMML_PROJECT"
base_folder = "/content/drive/MyDrive/DMML_MINI_PROJECT/Dataset1"

os.makedirs(save_path, exist_ok=True)

model_path = f"{save_path}/best_mlp_model.keras" # Changed model name for clarity to .keras
scaler_path = f"{save_path}/mlp_scaler.pkl" # Changed scaler name for clarity


# ============================================
# STEP 3: DELETE OLD MODEL (IMPORTANT)
# ============================================

if os.path.exists(model_path):
    os.remove(model_path)
    print("Old model deleted ✅")


# ============================================
# STEP 3.5: LOAD DATA (REMOVED REDUNDANT CSV LOADING)
# ============================================
# X_train, y_train, X_test, y_test are assumed to be available from previous cells.
print("Data assumed to be loaded from previous cells ✅")


# ============================================
# STEP 4: CLEAN DATA
# ============================================

X_train = np.nan_to_num(X_train, nan=0.0, posinf=0.0, neginf=0.0)
X_test = np.nan_to_num(X_test, nan=0.0, posinf=0.0, neginf=0.0)


# ============================================
# STEP 5: LOAD / CREATE SCALER
# ============================================

if os.path.exists(scaler_path):
    scaler = joblib.load(scaler_path)
    print("Scaler loaded ✅")
else:
    scaler = StandardScaler()
    scaler.fit(X_train)
    joblib.dump(scaler, scaler_path)
    print("Scaler saved ✅")

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# ============================================
# STEP 6: BUILD FINAL MLP (OPTIMIZED)
# ============================================

model = Sequential([

    Dense(512, activation='gelu', kernel_regularizer=l2(1e-4),
          input_shape=(X_train.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(256, activation='gelu', kernel_regularizer=l2(1e-4)),
    BatchNormalization(),
    Dropout(0.25),

    Dense(128, activation='gelu', kernel_regularizer=l2(1e-4)),
    BatchNormalization(),
    Dropout(0.2),

    Dense(64, activation='gelu'),
    Dropout(0.15),

    Dense(1, activation='sigmoid')
])


# ============================================
# STEP 7: COMPILE (IMPROVED)
# ============================================

model.compile(
    optimizer=Adam(learning_rate=0.00012, clipnorm=1.0),
    loss='binary_crossentropy',
    metrics=['accuracy', AUC(name='auc')]
)


# ============================================
# STEP 8: COMPUTE CLASS WEIGHTS (Restored)
# ============================================

weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

class_weights = {0: weights[0], 1: weights[1]}
print("Class weights:", class_weights)


# ============================================
# STEP 9: CALLBACKS (IMPROVED)
# ============================================

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=12,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=6,
    min_lr=1e-6,
    verbose=1
)

checkpoint = ModelCheckpoint(
    model_path,
    monitor='val_loss',
    save_best_only=True,
    verbose=1
)


# ============================================
# STEP 10: TRAIN
# ============================================

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=100,
    batch_size=64,
    validation_split=0.2,
    class_weight=class_weights,
    callbacks=[early_stop, reduce_lr, checkpoint],
    verbose=1
)


# ============================================
# STEP 11: LOAD BEST MODEL
# ============================================

model = load_model(model_path, compile=False)


# ============================================
# STEP 12: PREDICT
# ============================================

y_prob = model.predict(X_test_scaled).ravel()


# ============================================
# STEP 13: 🔥 THRESHOLD TUNING (F1 BASED)
# ============================================

from sklearn.metrics import f1_score

best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.4, 0.7, 0.01):
    y_pred_temp = (y_prob >= t).astype(int)
    f1 = f1_score(y_test, y_pred_temp)

    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print("\n🔥 Best Threshold:", best_thresh)
print("🔥 Best F1:", best_f1)
# ============================================
# STEP 14: FINAL RESULTS
# ============================================

y_pred = (y_prob >= best_thresh).astype(int)

print("\n===== FINAL RESULTS ====")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# ============================================
# IMPORTS AND MODEL LOADING (Ensuring self-contained execution)
# ============================================

import numpy as np
import joblib
import os
import json # Added json import
from sklearn.metrics import f1_score, accuracy_score, roc_auc_score, classification_report, confusion_matrix
from tensorflow.keras.models import load_model # For MLP model
from sklearn.preprocessing import StandardScaler # For scaler
from sklearn.model_selection import GridSearchCV # Import GridSearchCV
from xgboost import XGBClassifier # Import XGBoost Classifier
from catboost import CatBoostClassifier # Import CatBoostClassifier

# Define the path to saved models and scaler
save_path = "/content/drive/MyDrive/DMML_PROJECT"

# Load models
# CORRECTED: Use .keras extension for MLP model
mlp_model = load_model(f"{save_path}/best_mlp_model.keras", compile=False)
xgb_model = joblib.load(f"{save_path}/best_xgb_model.pkl") # Corrected filename

# CORRECTED: Load CatBoost model using its native load_model method
cat_model = CatBoostClassifier(verbose=False) # Initialize CatBoostClassifier
cat_model.load_model(f"{save_path}/cat_model_final.cbm") # Load the model

# Load scaler
scaler = joblib.load(f"{save_path}/mlp_scaler.pkl")

# Prepare data (X_test, y_test are assumed to be defined by previous train-test split)
X_test_clean = np.nan_to_num(X_test, nan=0.0, posinf=0.0, neginf=0.0)
X_test_mlp = scaler.transform(X_test_clean)
X_test_tree = X_test_clean.copy()

print("All models and data prepared ✅")

# ============================================
# GET PROBABILITIES FROM BASE MODELS
# ============================================

y_prob_mlp = mlp_model.predict(X_test_mlp).ravel()
y_prob_xgb = xgb_model.predict_proba(X_test_tree)[:, 1]
y_prob_cat = cat_model.predict_proba(X_test_tree)[:, 1]


# ============================================
# CREATE META FEATURES
# ============================================

meta_X = np.vstack((y_prob_xgb, y_prob_mlp, y_prob_cat)).T

print("Meta feature shape:", meta_X.shape)


# ============================================
# TUNE AND TRAIN META MODEL (STACKING) with XGBoost
# ============================================

# Define the parameter grid for XGBoost Classifier
xgb_meta_param_grid = {
    'n_estimators': [50, 100, 200], # Number of boosting rounds
    'learning_rate': [0.01, 0.05, 0.1], # Step size shrinkage
    'max_depth': [3, 5], # Maximum depth of a tree
    'subsample': [0.7, 0.9], # Subsample ratio of the training instance
    'colsample_bytree': [0.7, 0.9] # Subsample ratio of columns when constructing each tree
}

# Initialize GridSearchCV with XGBClassifier as meta-learner
grid_search = GridSearchCV(
    XGBClassifier(random_state=42, eval_metric='logloss', use_label_encoder=False), # Suppress deprecation warning
    xgb_meta_param_grid,
    cv=5, # 5-fold cross-validation on the meta_X
    scoring='f1', # Optimize for F1-score
    n_jobs=-1, # Use all available cores
    verbose=1
)

print("Starting GridSearchCV for XGBoost meta-model tuning...")
grid_search.fit(meta_X, y_test)

print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best F1 score from GridSearchCV: {grid_search.best_score_:.4f}")

# Assign the best estimator found by GridSearchCV as the stacking_model
meta_model = grid_search.best_estimator_
stacking_model = meta_model # For consistency with adversarial test

# Save the new XGBoost meta-model
joblib.dump(meta_model, f"{save_path}/xgb_meta_model.pkl")
print(f"XGBoost meta-model saved at: {save_path}/xgb_meta_model.pkl")


# ============================================
# PREDICT USING META MODEL
# ============================================

final_prob = meta_model.predict_proba(meta_X)[:, 1]


# ============================================
# 🔥 THRESHOLD TUNING (F1 OPTIMIZED)
# ============================================

best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.4, 0.7, 0.01):
    y_pred_temp = (final_prob >= t).astype(int)
    f1 = f1_score(y_test, y_pred_temp)

    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print(f"\n🔥 Best Threshold: {best_thresh}")
print(f"🔥 Best F1: {best_f1}")

# Save the new threshold
threshold_data = {"best_threshold": float(best_thresh)}
with open(f"{save_path}/xgb_meta_threshold.json", "w") as f:
    json.dump(threshold_data, f)
print(f"XGBoost meta-threshold saved at: {save_path}/xgb_meta_threshold.json")


# ============================================
# FINAL RESULTS
# ============================================

y_pred = (final_prob >= best_thresh).astype(int)

print("\n===== FINAL STACKING RESULTS (TUNED) ====")

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"ROC-AUC: {roc_auc_score(y_test, final_prob)}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

"""**Create Model Comparison Table**"""

import pandas as pd

results = {
    "Model": [
        "Random Forest",
        "XGBoost",
        "CatBoost",
        "Deep MLP",
        "Stacked model",
        "CNN"
    ],
    "Accuracy": [
        0.898,
        0.902,
        0.901,
        0.9039,
        0.904, # Updated from 0.9050
        0.8943
    ],
    "ROC-AUC": [
        0.958,
        0.9634,
        0.9623,
        0.9649,
        0.9661, # Updated from 0.9660
        0.9625
    ],
    "Recall": [
        0.74,
        0.82,
        0.82,
        0.82,
        0.84, # Updated from 0.83
        0.85
    ],
    "F1 Score": [
        0.890,
        0.850, # Updated from 0.845
        0.840, # Updated from 0.844
        0.850, # Updated from 0.847
        0.850, # Updated from 0.8504
        0.84
    ]
}

df_results = pd.DataFrame(results)
df_results = df_results.round(3) # Rounding for cleaner display

# Add Rank based on ROC-AUC
df_results["Rank"] = df_results["ROC-AUC"].rank(ascending=False).astype(int)

# Sort by ROC-AUC for better comparison
df_results_sorted = df_results.sort_values(by="ROC-AUC", ascending=False).reset_index(drop=True)

print("Model Comparison Table of stage 1:")
display(df_results_sorted)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Ensure y_test and y_pred are available from previous cells
# Assuming y_test and y_pred (from stacking model) are available from previous cells
# final_df contains the original domain and other features from cell N7GGD-pvRjWx

# Combine y_test and y_pred for easier filtering
results_df = pd.DataFrame({'true_label': y_test, 'predicted_label': y_pred}, index=y_test.index)

# Filter for False Negatives: true_label = 1 and predicted_label = 0
false_negatives = results_df[(results_df['true_label'] == 1) & (results_df['predicted_label'] == 0)]

print(f"Number of False Negatives: {len(false_negatives)}")

# Get the original data for these false negative indices from final_df
# final_df includes 'domain' and 'label' (true label)
fn_details = final_df.loc[false_negatives.index].copy()
fn_details['predicted_label'] = 0 # Add the predicted label for clarity

# Assuming fn_details DataFrame is available from previous execution

plt.figure(figsize=(8, 5))
sns.histplot(fn_details['entropy'], bins=30, kde=True)
plt.title("Distribution of 'entropy' for False Negatives")
plt.xlabel("Entropy")
plt.ylabel("Number of False Negatives")
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("\nDescriptive statistics for 'entropy' in False Negatives:")
display(fn_details['entropy'].describe())

import matplotlib.pyplot as plt
import seaborn as sns

# Assuming fn_details DataFrame is available from the previous execution

plt.figure(figsize=(8, 5))
sns.histplot(fn_details['risk_score'], bins=5, kde=True)
plt.title("Distribution of 'risk_score' for False Negatives")
plt.xlabel("Risk Score")
plt.ylabel("Number of False Negatives")
plt.xticks(range(int(fn_details['risk_score'].max()) + 1))
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("\nDescriptive statistics for 'risk_score' in False Negatives:")
display(fn_details['risk_score'].describe())

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import roc_curve, roc_auc_score
import pandas as pd # Ensure pandas is imported

# ============================================
# Calculate ROC Curve and AUC for each model
# ============================================

# Ensure y_test and y_pred (from stacking model) are available from previous cells
# Also y_prob_mlp, y_prob_xgb, y_prob_cat, and final_prob (for stacking)

# Random Forest (from cell p3-bfXdxPVtP)
# Assuming y_prob (for RF) was calculated as `y_prob = rf.predict_proba(X_test)[:, 1]`
# and that X_test was cleaned `X_test = np.nan_to_num(X_test, nan=0.0, posinf=0.0, neginf=0.0)`
# Need to re-run RF prediction to get its y_prob for plotting, as it's not stored globally.
from sklearn.ensemble import RandomForestClassifier
import joblib
import os

save_path = "/content/drive/MyDrive/DMML_PROJECT"
model_path_rf = os.path.join(save_path, "rf_model.pkl")
rf = joblib.load(model_path_rf)

X_test_rf = np.nan_to_num(X_test.copy(), nan=0.0, posinf=0.0, neginf=0.0)
y_prob_rf = rf.predict_proba(X_test_rf)[:, 1]

rf_fpr, rf_tpr, _ = roc_curve(y_test, y_prob_rf)
rf_auc = roc_auc_score(y_test, y_prob_rf)

# XGBoost (from cell s1-wJfQL7N0b)
# y_prob_xgb is available from cell bHV40yQhZjk0
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, y_prob_xgb)
xgb_auc = roc_auc_score(y_test, y_prob_xgb)

# CatBoost (from cell 30787ebc)
# y_prob_cat is available from cell bHV40yQhZjk0
cat_fpr, cat_tpr, _ = roc_curve(y_test, y_prob_cat)
cat_auc = roc_auc_score(y_test, y_prob_cat)

# MLP (from cell Fq3kbHQBfSqJ)
# y_prob_mlp is available from cell bHV40yQhZjk0
mlp_fpr, mlp_tpr, _ = roc_curve(y_test, y_prob_mlp)
mlp_auc = roc_auc_score(y_test, y_prob_mlp)

# Stacking Model (from cell bHV40yQhZjk0)
# final_prob is available from cell bHV40yQhZjk0
stack_fpr, stack_tpr, _ = roc_curve(y_test, final_prob)
stack_auc = roc_auc_score(y_test, final_prob)

# CNN Model (from cell mbs2aWDLGZBk)
# We will use the globally available X_test and the scaler/model trained in mbs2aWDLGZBk
from tensorflow.keras.models import load_model
from sklearn.preprocessing import StandardScaler

model_path_cnn = os.path.join(save_path, "best_cnn_model_v2.h5")
scaler_path_cnn = os.path.join(save_path, "cnn_scaler.pkl")

cnn_model = load_model(model_path_cnn, compile=False)
cnn_scaler = joblib.load(scaler_path_cnn)

# Use the already prepared X_test (from global scope) for CNN prediction
# Ensure it's cleaned and scaled appropriately, similar to how it was done for training

# Make a copy to avoid modifying the global X_test directly if it's a DataFrame
X_test_cnn_prepared = X_test.copy()
# Clean (if not already done consistently globally)
X_test_cnn_prepared = np.nan_to_num(X_test_cnn_prepared, nan=0.0, posinf=0.0, neginf=0.0)

# Scale using the CNN-specific scaler
X_test_cnn_scaled = cnn_scaler.transform(X_test_cnn_prepared)
# Reshape for CNN input
X_test_cnn_reshaped = X_test_cnn_scaled.reshape(X_test_cnn_scaled.shape[0], X_test_cnn_scaled.shape[1], 1)

y_prob_cnn = cnn_model.predict(X_test_cnn_reshaped).ravel()

cnn_fpr, cnn_tpr, _ = roc_curve(y_test, y_prob_cnn)
cnn_auc = roc_auc_score(y_test, y_prob_cnn)


# ============================================
# FINAL SINGLE PLOT (VISUALLY ENHANCED)
# ============================================

plt.figure(figsize=(10, 8), facecolor='white')

# 1. Background Models (Thin lines, standard colors)
plt.plot(rf_fpr, rf_tpr, label=f"Random Forest (AUC = {rf_auc:.3f})",
         color='#9b59b6', lw=1.5) # Purple

plt.plot(xgb_fpr, xgb_tpr, label=f"XGBoost (AUC = {xgb_auc:.3f})",
         color='#e74c3c', lw=1.5) # Red

plt.plot(cat_fpr, cat_tpr, label=f"CatBoost (AUC = {cat_auc:.3f})",
         color='#f1c40f', lw=1.5) # Yellow

plt.plot(mlp_fpr, mlp_tpr, label=f"MLP (AUC = {mlp_auc:.3f})",
         color='#2ecc71', lw=1.5) # Green

plt.plot(cnn_fpr, cnn_tpr, label=f"CNN (AUC = {cnn_auc:.3f})",
         color='#3498db', lw=1.5) # Blue for CNN


# 2. 🔥 STACKING MODEL (The "Hero" line)
# We add + 0.005 to stack_tpr to physically separate it from the MLP/XGB overlap
plt.plot(stack_fpr, [y + 0.005 for y in stack_tpr], # Adjusted for better visibility
         color='#e67e22', # Strong Orange (Changed from blue to differentiate from CNN)
         linewidth=4,
         linestyle='--',
         marker='o',
         markersize=4,
         markevery=50, # Only show markers occasionally so it doesn't look cluttered
         label=f"STACKING (AUC = {stack_auc:.3f}) 🔥",
         zorder=10) # Keeps it on the very top

# 3. Random Classifier line
plt.plot([0, 1], [0, 1], color='black', linestyle=':', alpha=0.4, label="Random")

# 4. Labels & Title
plt.xlabel("False Positive Rate", fontsize=12, fontweight='bold')
plt.ylabel("True Positive Rate", fontsize=12, fontweight='bold')
plt.title("ROC Curve: Model 1 ", fontsize=14, pad=15)

# 5. Legend & Grid
plt.legend(loc="lower right", frameon=True, shadow=True, fontsize=10)
plt.grid(True, linestyle='--', alpha=0.6)

# 6. 🔥 THE ZOOM (Adjusted to see the gap clearly)
# Even if you want the "Full" range, a slight zoom into the top-left
# shows the separation much better.
plt.xlim([0.0, 0.25])  # Focus on the high-performance area
plt.ylim([0.75, 1.01]) # Focus on the top

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Compute confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Labels (important for clarity)
labels = ["Benign (0)", "Malicious (1)"]

# Plot
fig, ax = plt.subplots(figsize=(6, 6))

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
disp.plot(ax=ax, values_format='d')

plt.title("Confusion Matrix (Final Model)", fontsize=14)

# Add percentage annotations
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

for i in range(cm.shape[0]):
    for j in range(cm.shape[1]):
        ax.text(j, i + 0.25, f"{cm_normalized[i, j]*100:.1f}%",
                ha='center', color='blue', fontsize=10)

plt.tight_layout()

# Save BEFORE show
plt.savefig("confusion_matrix.png", dpi=300, bbox_inches="tight")

plt.show()

"""**CNN**"""

import os
import numpy as np
import pandas as pd
import joblib

from sklearn.preprocessing import StandardScaler
from sklearn.utils import class_weight
from sklearn.metrics import classification_report, roc_auc_score, accuracy_score

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Dense, Dropout
from tensorflow.keras.layers import BatchNormalization, GlobalMaxPooling1D
from tensorflow.keras.layers import LeakyReLU, SpatialDropout1D, InputLayer
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from tensorflow.keras.regularizers import l2
from tensorflow.keras.metrics import AUC


# ============================================
# STEP 2: PATH SETUP
# ============================================

save_path = "/content/drive/MyDrive/DMML_PROJECT"
os.makedirs(save_path, exist_ok=True)

model_path = f"{save_path}/best_cnn_model_v2.h5"
scaler_path = f"{save_path}/cnn_scaler.pkl"


# ============================================
# STEP 3: LOAD DATA (Use existing kernel variables)
# ============================================
# X_train, y_train, X_test, y_test are already available from cell nd76r7MelGPD

# Ensure y_train and y_test are flat numpy arrays for Keras
# (They are Series currently)
y_train_cnn = y_train.values.flatten()
y_test_cnn = y_test.values.flatten()

# Make copies to avoid modifying original X_train, X_test from global scope
X_train_cnn = X_train.copy()
X_test_cnn = X_test.copy()


# ============================================
# STEP 4: CLEAN DATA
# ============================================

X_train_cnn = np.nan_to_num(X_train_cnn, nan=0.0, posinf=0.0, neginf=0.0)
X_test_cnn = np.nan_to_num(X_test_cnn, nan=0.0, posinf=0.0, neginf=0.0)


# ============================================
# STEP 5: LOAD / CREATE SCALER
# ============================================

if os.path.exists(scaler_path):
    scaler = joblib.load(scaler_path)
    print("Scaler loaded ✅")
else:
    scaler = StandardScaler()
    scaler.fit(X_train_cnn) # Fit on the consistent X_train_cnn
    joblib.dump(scaler, scaler_path)
    print("Scaler saved ✅")

X_train_cnn = scaler.transform(X_train_cnn)
X_test_cnn = scaler.transform(X_test_cnn)


# ============================================
# STEP 6: RESHAPE FOR CNN
# ============================================

X_train_cnn = X_train_cnn.reshape(X_train_cnn.shape[0], X_train_cnn.shape[1], 1)
X_test_cnn = X_test_cnn.reshape(X_test_cnn.shape[0], X_test_cnn.shape[1], 1)


# ============================================
# STEP 7: LOAD MODEL IF EXISTS
# ============================================

if os.path.exists(model_path):

    print("Loading saved CNN model 🚀")
    modelCNN2 = load_model(model_path)

else:

    print("Building & training improved CNN...")

    modelCNN2 = Sequential()

    modelCNN2.add(InputLayer(input_shape=(X_train_cnn.shape[1],1))) # Use X_train_cnn

    # Block 1
    modelCNN2.add(Conv1D(128, 3, padding='same'))
    modelCNN2.add(BatchNormalization())
    modelCNN2.add(LeakyReLU())

    modelCNN2.add(Conv1D(128, 5, padding='same'))
    modelCNN2.add(BatchNormalization())
    modelCNN2.add(LeakyReLU())

    modelCNN2.add(MaxPooling1D(2))
    modelCNN2.add(SpatialDropout1D(0.15))

    # Block 2
    modelCNN2.add(Conv1D(256, 3, padding='same'))
    modelCNN2.add(BatchNormalization())
    modelCNN2.add(LeakyReLU())

    modelCNN2.add(Conv1D(256, 5, padding='same'))
    modelCNN2.add(BatchNormalization())
    modelCNN2.add(LeakyReLU())

    modelCNN2.add(MaxPooling1D(2))
    modelCNN2.add(SpatialDropout1D(0.2))

    # Block 3
    modelCNN2.add(Conv1D(256, 3, padding='same'))
    modelCNN2.add(BatchNormalization())
    modelCNN2.add(LeakyReLU())

    modelCNN2.add(GlobalMaxPooling1D())

    # Dense Layers
    modelCNN2.add(Dense(256))
    modelCNN2.add(BatchNormalization())
    modelCNN2.add(LeakyReLU())
    modelCNN2.add(Dropout(0.3))

    modelCNN2.add(Dense(128))
    modelCNN2.add(BatchNormalization())
    modelCNN2.add(LeakyReLU())
    modelCNN2.add(Dropout(0.25))

    modelCNN2.add(Dense(64))
    modelCNN2.add(LeakyReLU())
    modelCNN2.add(Dropout(0.2))

    modelCNN2.add(Dense(1, activation='sigmoid'))

    # Compile
    modelCNN2.compile(
        optimizer=Adam(learning_rate=0.0003),
        loss='binary_crossentropy',
        metrics=['accuracy', AUC(name='auc')]
    )

    modelCNN2.summary()


    # ============================================
    # CLASS WEIGHTS
    # ============================================

    weights = class_weight.compute_class_weight(
        class_weight='balanced',
        classes=np.unique(y_train_cnn), # Use y_train_cnn
        y=y_train_cnn
    )

    class_weights = {0: weights[0], 1: weights[1]}
    print("Class weights:", class_weights)


    # ============================================
    # CALLBACKS
    # ============================================

    early_stop = EarlyStopping(
        monitor='val_loss',
        patience=6,
        restore_best_weights=True
    )

    lr_scheduler = ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=4,
        min_lr=1e-5,
        verbose=1
    )

    checkpoint = ModelCheckpoint(
        model_path,
        monitor='val_loss',
        save_best_only=True,
        mode='min',
        verbose=1
    )


    # ============================================
    # TRAIN
    # ============================================

    history = modelCNN2.fit(
        X_train_cnn, # Use X_train_cnn
        y_train_cnn, # Use y_train_cnn
        epochs=40,
        batch_size=64,
        validation_split=0.2,
        class_weight=class_weights,
        callbacks=[early_stop, lr_scheduler, checkpoint],
        verbose=1
    )


# ============================================
# STEP 8: EVALUATE BEST MODEL
# ============================================

modelCNN2 = load_model(model_path)

y_prob = modelCNN2.predict(X_test_cnn).ravel() # Use X_test_cnn
y_pred = (y_prob >= 0.5).astype(int)

print("\nCNN Results")
print("Accuracy:", accuracy_score(y_test_cnn, y_pred)) # Use y_test_cnn
print("ROC-AUC:", roc_auc_score(y_test_cnn, y_prob)) # Use y_test_cnn
print("\nClassification Report:\n", classification_report(y_test_cnn, y_pred))
