# -*- coding: utf-8 -*-
"""Phase 2 of DMML MINI Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7ppd6SOSTVAvWRiHiANNwtoDuvXr75O
"""

# ============================================
# FULL DATASET: DOMAIN-LEVEL CREATION
# (Using SAME variable names for pipeline compatibility)
# ============================================

import kagglehub
import os
import pandas as pd
from urllib.parse import urlparse

# -------------------------------
# Step A: Download Dataset
# -------------------------------
path = kagglehub.dataset_download("sid321axn/malicious-urls-dataset")
print("Dataset folder path:", path)

files = os.listdir(path)
print("Files inside dataset folder:", files)

csv_path = os.path.join(path, files[0])
df = pd.read_csv(csv_path)

print("\nOriginal dataset shape:", df.shape)
print("Original class distribution:")
print(df['type'].value_counts())


# -------------------------------
# Step B: Extract Domain Safely
# -------------------------------

def extract_domain_safe(url):
    try:
        parsed = urlparse(url)

        if not parsed.netloc:
            parsed = urlparse("http://" + url)

        domain = parsed.netloc

        if domain.startswith("www."):
            domain = domain[4:]

        return domain.lower()

    except Exception:
        return None


df['domain'] = df['url'].apply(extract_domain_safe)

print("\nSample after domain extraction:")
print(df[['url','domain']].head())


# -------------------------------
# Step C: Remove Invalid Domains
# -------------------------------
df = df.dropna(subset=['domain'])
print("\nAfter removing invalid domains:")
print("Dataset shape:", df.shape)


# -------------------------------
# Step D: Remove Duplicate Domains
# -------------------------------
df = df.drop_duplicates(subset='domain')
print("\nAfter removing duplicate domains:")
print("Dataset shape:", df.shape)


# -------------------------------
# Step E: Convert Multi-class to Binary
# -------------------------------

def convert_label(x):
    if x == 'benign':
        return 0
    else:
        return 1

df['label'] = df['type'].apply(convert_label)

print("\nBinary class distribution:")
print(df['label'].value_counts())


# -------------------------------
# Step F: Use SAME Variable Name (balanced_df)
# -------------------------------

# IMPORTANT: We keep variable name as balanced_df
# but now it contains FULL dataset (no sampling)

balanced_df = df.copy().reset_index(drop=True)

print("\nUsing FULL dataset:")
print(balanced_df['label'].value_counts())
print("Dataset shape:", balanced_df.shape)


# -------------------------------
# Step G: Keep Only Required Columns
# -------------------------------

final_df = balanced_df[['domain','label']].copy()

print("\nFinal Dataset Preview:")
print(final_df.head())
print("Final dataset shape:", final_df.shape)


# -------------------------------
# Step H: Save Dataset
# -------------------------------

final_df.to_csv("full_domain_dataset.csv", index=False)

print("\nFull dataset saved successfully!")

# ============================================
# PART 2: FEATURE ENGINEERING (FIXED VERSION)
# ============================================

import numpy as np
import re
import math

# IMPORTANT FIX → use .copy() to avoid SettingWithCopyWarning
final_df = balanced_df[['domain','label']].copy()

# -------------------------------
# Lexical Features
# -------------------------------

# 1. Domain Length
final_df.loc[:, 'domain_length'] = final_df['domain'].apply(len)

# 2. Dot Count (Subdomain levels)
final_df.loc[:, 'dot_count'] = final_df['domain'].apply(lambda x: x.count('.'))

# 3. Hyphen Count
final_df.loc[:, 'hyphen_count'] = final_df['domain'].apply(lambda x: x.count('-'))

# 4. Digit Count
final_df.loc[:, 'digit_count'] = final_df['domain'].apply(lambda x: sum(c.isdigit() for c in x))

# 5. Digit Ratio
final_df.loc[:, 'digit_ratio'] = final_df['digit_count'] / final_df['domain_length']

# 6. Special Character Count
final_df.loc[:, 'special_char_count'] = final_df['domain'].apply(
    lambda x: len(re.findall(r'[^a-zA-Z0-9.-]', x))
)

# 7. Vowel Count
final_df.loc[:, 'vowel_count'] = final_df['domain'].apply(
    lambda x: sum(c in 'aeiou' for c in x)
)

# 8. Vowel Ratio
final_df.loc[:, 'vowel_ratio'] = final_df['vowel_count'] / final_df['domain_length']

# 9. Consonant Count
final_df.loc[:, 'consonant_count'] = final_df['domain'].apply(
    lambda x: sum(c.isalpha() and c not in 'aeiou' for c in x)
)

# 10. Shannon Entropy
def shannon_entropy(domain):
    prob = [float(domain.count(c)) / len(domain) for c in dict.fromkeys(list(domain))]
    entropy = - sum([p * math.log2(p) for p in prob])
    return entropy

final_df.loc[:, 'entropy'] = final_df['domain'].apply(shannon_entropy)
# IMPORTANT: use original df with full URLs

balanced_df = balanced_df.copy()

# 1. URL Length
balanced_df['url_length'] = balanced_df['url'].apply(len)

# 2. Path Length
balanced_df['path_length'] = balanced_df['url'].apply(
    lambda x: len(urlparse(x).path)
)

# 3. Query Length
balanced_df['query_length'] = balanced_df['url'].apply(
    lambda x: len(urlparse(x).query)
)

# 4. URL Depth (Number of '/')
balanced_df['url_depth'] = balanced_df['url'].apply(
    lambda x: urlparse(x).path.count('/')
)

# 5. Number of Parameters
balanced_df['param_count'] = balanced_df['url'].apply(
    lambda x: urlparse(x).query.count('&') + 1 if urlparse(x).query else 0
)

# 6. Suspicious File Extension
suspicious_ext = ['.exe','.zip','.rar','.js','.php','.scr','.bat']

def suspicious_extension(url):
    for ext in suspicious_ext:
        if url.lower().endswith(ext):
            return 1
    return 0

balanced_df['suspicious_extension'] = balanced_df['url'].apply(suspicious_extension)

# 7. Encoded Characters (%)
balanced_df['encoded_char_count'] = balanced_df['url'].apply(
    lambda x: x.count('%')
)

# 8. Multiple Subdomains
balanced_df['multiple_subdomains'] = balanced_df['domain'].apply(
    lambda x: 1 if x.count('.') > 2 else 0
)


# -------------------------------
# CTI-Inspired Features
# -------------------------------

# 11. Suspicious TLD Flag
suspicious_tlds = ['xyz','tk','top','club','work','gq','cf','ml','ga']

def suspicious_tld(domain):
    tld = domain.split('.')[-1]
    return 1 if tld in suspicious_tlds else 0

final_df.loc[:, 'suspicious_tld_flag'] = final_df['domain'].apply(suspicious_tld)

# 12. Suspicious Keyword Flag
keywords = ['login','verify','secure','account','update','bank','paypal','signin','confirm']

def suspicious_keyword(domain):
    for word in keywords:
        if word in domain:
            return 1
    return 0

final_df.loc[:, 'suspicious_keyword_flag'] = final_df['domain'].apply(suspicious_keyword)

# 13. Length Anomaly (>25 characters)
final_df.loc[:, 'length_anomaly'] = final_df['domain_length'].apply(
    lambda x: 1 if x > 25 else 0
)

# 14. Contains IP Address
def contains_ip(domain):
    pattern = r'\d+\.\d+\.\d+\.\d+'
    return 1 if re.search(pattern, domain) else 0

final_df.loc[:, 'contains_ip'] = final_df['domain'].apply(contains_ip)

# 15. Risk Score (Combined Heuristic CTI Score)
final_df.loc[:, 'risk_score'] = (
    final_df['suspicious_tld_flag'] +
    final_df['suspicious_keyword_flag'] +
    final_df['length_anomaly'] +
    final_df['contains_ip']
)

print("Feature Engineering Completed Successfully ✅")
print("Final dataset shape:", final_df.shape)
print("\nFinal dataset preview:")
print(final_df.head())

import numpy as np
import re
import math
from urllib.parse import urlparse
from collections import Counter
from itertools import groupby
from difflib import SequenceMatcher
import pandas as pd # Ensure pandas is imported if not already
import kagglehub
import os

# Check if balanced_df exists, if not, re-create it from original data source
if 'balanced_df' not in locals() and 'balanced_df' not in globals():
    print("balanced_df not found. Re-running essential data loading and preprocessing from COuFeJMYc3sW.")
    # ------------------------------- # Step A: Download Dataset
    path = kagglehub.dataset_download("sid321axn/malicious-urls-dataset")
    files = os.listdir(path)
    csv_path = os.path.join(path, files[0])
    df = pd.read_csv(csv_path)

    # ------------------------------- # Step B: Extract Domain Safely
    def extract_domain_safe(url):
        try:
            parsed = urlparse(url)
            if not parsed.netloc:
                parsed = urlparse("http://" + url)
            domain = parsed.netloc
            if domain.startswith("www."):
                domain = domain[4:]
            return domain.lower()
        except Exception:
            return None

    df['domain'] = df['url'].apply(extract_domain_safe)
    # ------------------------------- # Step C: Remove Invalid Domains
    df = df.dropna(subset=['domain'])
    # ------------------------------- # Step D: Remove Duplicate Domains
    df = df.drop_duplicates(subset='domain')
    # ------------------------------- # Step E: Convert Multi-class to Binary
    def convert_label(x):
        if x == 'benign':
            return 0
        else:
            return 1
    df['label'] = df['type'].apply(convert_label)
    # ------------------------------- # Step F: Use SAME Variable Name (balanced_df)
    balanced_df = df.copy().reset_index(drop=True)
    print("balanced_df successfully re-created for feature engineering.")


# Keep same variable
final_df = balanced_df[['domain','label']].copy()

# IMPORTANT FIX: Remove rows with empty domains that would cause ZeroDivisionError
final_df = final_df[final_df['domain'].str.len() > 0].copy()

# -------------------------------
# BASIC LEXICAL FEATURES (DOMAIN-LEVEL)
# -------------------------------

final_df['domain_length'] = final_df['domain'].apply(len)
final_df['dot_count'] = final_df['domain'].apply(lambda x: x.count('.'))
final_df['hyphen_count'] = final_df['domain'].apply(lambda x: x.count('-'))
final_df['digit_count'] = final_df['domain'].apply(lambda x: sum(c.isdigit() for c in x))

# FIX: Corrected calculation for digit_ratio and vowel_ratio
final_df['digit_ratio'] = final_df['digit_count'] / final_df['domain_length'].replace(0, np.nan)

final_df['special_char_count'] = final_df['domain'].apply(
    lambda x: len(re.findall(r'[^a-zA-Z0-9.-]', x))
)

final_df['vowel_count'] = final_df['domain'].apply(
    lambda x: sum(c in 'aeiou' for c in x)
)

# FIX: Corrected calculation for vowel_ratio
final_df['vowel_ratio'] = final_df['vowel_count'] / final_df['domain_length'].replace(0, np.nan)

final_df['consonant_count'] = final_df['domain'].apply(
    lambda x: sum(c.isalpha() and c not in 'aeiou' for c in x)
)

# Fill any NaN created by division by zero (if domain_length was 0)
final_df = final_df.fillna(0)

# NEW LEXICAL FEATURES (DOMAIN-LEVEL)
final_df['domain_uppercase_ratio'] = final_df['domain'].apply(
    lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0
)
final_df['longest_domain_token'] = final_df['domain'].apply(
    lambda x: max((len(w) for w in x.split('.')), default=0)
)


# -------------------------------
# ENTROPY FEATURES (DOMAIN-LEVEL)
# -------------------------------

def shannon_entropy(domain_or_url):
    prob = [float(domain_or_url.count(c)) / len(domain_or_url) for c in set(domain_or_url)]
    return -sum([p * math.log2(p) for p in prob])

final_df['entropy'] = final_df['domain'].apply(shannon_entropy)

# NEW: Subdomain entropy
final_df['subdomain_entropy'] = final_df['domain'].apply(
    lambda x: shannon_entropy(x.split('.')[0]) if x.split('.')[0] else 0 # Handle empty subdomain case
)

# -------------------------------
# URL FEATURES (APPLIED TO balanced_df THEN MERGED)
# -------------------------------

balanced_df['url_length'] = balanced_df['url'].apply(len)

balanced_df['path'] = balanced_df['url'].apply(lambda x: urlparse(x).path)
balanced_df['path_length'] = balanced_df['path'].apply(len)

balanced_df['query'] = balanced_df['url'].apply(lambda x: urlparse(x).query) # Extract query part
balanced_df['query_length'] = balanced_df['query'].apply(len)

balanced_df['url_depth'] = balanced_df['path'].apply(lambda x: x.count('/'))

balanced_df['param_count'] = balanced_df['query'].apply(
    lambda x: x.count('&') + 1 if x else 0 # Use extracted query
)

# Suspicious extension
suspicious_ext = ['.exe','.zip','.rar','.js','.php','.scr','.bat']
balanced_df['suspicious_extension'] = balanced_df['url'].apply(
    lambda x: 1 if any(x.lower().endswith(ext) for ext in suspicious_ext) else 0
)

# Encoding features
balanced_df['encoded_char_count'] = balanced_df['url'].apply(lambda x: x.count('%'))
balanced_df['encoding_density'] = balanced_df['url'].apply(
    lambda x: x.count('%') / len(x) if len(x) > 0 else 0
) # Ensure no ZeroDivisionError

# HTTPS
balanced_df['has_https'] = balanced_df['url'].apply(
    lambda x: 1 if x.startswith("https") else 0
)

# Token count
balanced_df['token_count'] = balanced_df['url'].apply(
    lambda x: len(re.split(r'[./?=&-]', x))
)

# Path keyword detection
keywords_path = ['login','admin','secure','update','account']
balanced_df['path_keyword_flag'] = balanced_df['path'].apply(
    lambda x: 1 if any(k in x.lower() for k in keywords_path) else 0
)

# NEW URL-LEVEL FEATURES

# URL Entropy
balanced_df['url_entropy'] = balanced_df['url'].apply(shannon_entropy)

# URL Digit Ratio
balanced_df['url_digit_ratio'] = balanced_df['url'].apply(
    lambda x: sum(c.isdigit() for c in x) / len(x) if len(x) > 0 else 0
)

# URL Special Character Ratio
balanced_df['url_special_char_ratio'] = balanced_df['url'].apply(
    lambda x: sum(1 for c in x if not c.isalnum() and c not in ['/', '.', ':', '?','&', '=', '-']) / len(x) if len(x) > 0 else 0
)

# URL Vowel Ratio
balanced_df['url_vowel_ratio'] = balanced_df['url'].apply(
    lambda x: sum(1 for c in x.lower() if c in 'aeiou') / len(x) if len(x) > 0 else 0
)

# URL Consonant Ratio
balanced_df['url_consonant_ratio'] = balanced_df['url'].apply(
    lambda x: sum(1 for c in x.lower() if c.isalpha() and c not in 'aeiou') / len(x) if len(x) > 0 else 0
)

# Has Port
def has_port(url_str):
    parsed = urlparse(url_str)
    return 1 if parsed.port is not None else 0
balanced_df['has_port'] = balanced_df['url'].apply(has_port)

# Has @ symbol
balanced_df['has_at_symbol'] = balanced_df['url'].apply(lambda x: 1 if '@' in x else 0)

# Has double slash in path (e.g. example.com//path)
balanced_df['has_double_slash_in_path'] = balanced_df['path'].apply(lambda x: 1 if '//' in x else 0)


# Merge ALL URL features
url_features = [
    'url_length','path_length','query_length','url_depth',
    'param_count','suspicious_extension','encoded_char_count',
    'encoding_density','has_https','token_count','path_keyword_flag',
    # New URL Features
    'url_entropy', 'url_digit_ratio', 'url_special_char_ratio',
    'url_vowel_ratio', 'url_consonant_ratio', 'has_port',
    'has_at_symbol', 'has_double_slash_in_path'
]

for col in url_features:
    final_df[col] = balanced_df[col]

# -------------------------------
# CTI FEATURES
# -------------------------------

suspicious_tlds = ['xyz','tk','top','club','work','gq','cf','ml','ga']

final_df['suspicious_tld_flag'] = final_df['domain'].apply(
    lambda x: 1 if x.split('.')[-1] in suspicious_tlds else 0
)

keywords = ['login','verify','secure','account','update','bank','paypal','signin','confirm']

final_df['suspicious_keyword_flag'] = balanced_df['url'].apply(
    lambda x: 1 if any(word in x.lower() for word in keywords) else 0
)

final_df['length_anomaly'] = final_df['domain_length'].apply(lambda x: 1 if x > 25 else 0)

final_df['contains_ip'] = final_df['domain'].apply(
    lambda x: 1 if re.search(r'\d+\.\d+\.\d+\.\d+', x) else 0
)

# Brand impersonation
brands = ['google','facebook','amazon','paypal','apple','microsoft']
final_df['brand_flag'] = balanced_df['url'].apply(
    lambda x: 1 if any(b in x.lower() for b in brands) else 0
)

# Typosquatting score
def typo_score(domain):
    # Ensure domain is not empty before calculating similarity
    if not domain:
        return 0.0
    return max([SequenceMatcher(None, domain, b).ratio() for b in brands])

final_df['typosquat_score'] = final_df['domain'].apply(typo_score)

# Risk score
final_df['risk_score'] = (
    final_df['suspicious_tld_flag'] +
    final_df['suspicious_keyword_flag'] +
    final_df['length_anomaly'] +
    final_df['contains_ip'] +
    final_df['brand_flag']
)

# -------------------------------
# PATTERN FEATURES
# -------------------------------

# Unique char ratio
final_df['unique_char_ratio'] = final_df['domain'].apply(
    lambda x: len(set(x)) / len(x) if len(x) > 0 else 0
)

# Max repeated characters
final_df['max_repeated_char'] = final_df['domain'].apply(
    lambda x: max([len(list(g)) for _, g in groupby(x)]) if len(x) > 0 else 0 # Handle empty string
)

# -------------------------------
# SEQUENCE FEATURES
# -------------------------------

def longest_digit_seq(domain):
    max_seq = current = 0
    for c in domain:
        if c.isdigit():
            current += 1
            max_seq = max(max_seq, current)
        else:
            current = 0
    return max_seq

final_df['longest_digit_seq'] = final_df['domain'].apply(longest_digit_seq)

# -------------------------------
# BIGRAM RANDOMNESS
# -------------------------------

def generate_bigrams(domain):
    return [domain[i:i+2] for i in range(len(domain)-1)]

all_bigrams = []
# Ensure 'domain' column is iterated safely in case of empty strings
for d in final_df['domain'].dropna(): # Drop NaN domains before processing
    all_bigrams.extend(generate_bigrams(d))

bigram_counts = Counter(all_bigrams)
total_bigrams = sum(bigram_counts.values())

def bigram_score(domain):
    bigrams = generate_bigrams(domain)
    score = 0
    # Handle case where bigrams list is empty to prevent ZeroDivisionError
    if not bigrams or total_bigrams == 0: # Also check total_bigrams for 0
        return 0.0
    for bg in bigrams:
        freq = bigram_counts.get(bg, 0.5) / total_bigrams
        score += -math.log2(freq) if freq > 0 else 0 # Handle freq = 0 case
    return score / len(bigrams) if bigrams else 0

final_df['bigram_randomness'] = final_df['domain'].apply(bigram_score)

print("🚀 Advanced Feature Engineering Completed!")
print("Final shape:", final_df.shape)

# ============================================
# PART 3: EDA & FEATURE CORRELATION ANALYSIS
# ============================================

import matplotlib.pyplot as plt
import seaborn as sns

# --------------------------------
# 1. Class Distribution
# --------------------------------
plt.figure(figsize=(6,4))
sns.countplot(x='label', data=final_df)
plt.title("Class Distribution (0 = Benign, 1 = Malicious)")
plt.show()


# --------------------------------
# 2. Feature Distribution (Example)
# --------------------------------

plt.figure(figsize=(8,5))
sns.histplot(data=final_df, x='domain_length', hue='label', bins=40, kde=True)
plt.title("Domain Length Distribution by Class")
plt.show()


plt.figure(figsize=(8,5))
sns.histplot(data=final_df, x='entropy', hue='label', bins=40, kde=True)
plt.title("Entropy Distribution by Class")
plt.show()


# --------------------------------
# 3. Correlation Heatmap
# --------------------------------

# Drop non-numeric column
corr_df = final_df.drop(columns=['domain'])

plt.figure(figsize=(14,10))
sns.heatmap(corr_df.corr(), annot=False, cmap='coolwarm', center=0)
plt.title("Feature Correlation Heatmap")
plt.show()


# --------------------------------
# 4. Top Correlated Features with Label
# --------------------------------

label_corr = corr_df.corr()['label'].sort_values(ascending=False)

print("\nCorrelation with Label:")
print(label_corr)

# ============================================
# SAVE FINAL DATASET
# ============================================

# Save full dataset (with domain column)
final_df.to_csv("malicious_domain_features.csv", index=False)

# Save ML-ready dataset (drop domain column)
ml_ready_df = final_df.drop(columns=['domain']).copy()
ml_ready_df.to_csv("ml_ready_features.csv", index=False)

print("Datasets saved successfully ✅")
print("Full dataset shape:", final_df.shape)
print("ML-ready dataset shape:", ml_ready_df.shape)

# ============================================
# TRAIN-TEST SPLIT (70% TRAIN / 30% TEST)
# ============================================

from sklearn.model_selection import train_test_split

# Load ML-ready dataset (optional if restarting notebook)
# ml_ready_df = pd.read_csv("ml_ready_30k_features.csv")

# Separate features and target
X = ml_ready_df.drop(columns=['label'])
y = ml_ready_df['label']

print("Feature matrix shape:", X.shape)
print("Target vector shape:", y.shape)

# Train-test split (Stratified)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("\nTrain shape:", X_train.shape)
print("Test shape:", X_test.shape)

print("\nTrain label distribution:")
print(y_train.value_counts())

print("\nTest label distribution:")
print(y_test.value_counts())

# ============================================
# SAVE ALL DATASETS INTO:
# MyDrive/DMML_MINI_PROJECT/dataset
# ============================================
from google.colab import drive
drive.mount('/content/drive')
import os
import pandas as pd

# Define main folder path
base_folder = "/content/drive/MyDrive/DMML_MINI_PROJECT/Dataset1"

# Create folder if it doesn't exist
os.makedirs(base_folder, exist_ok=True)

# -----------------------------
# Save Full Dataset (with domain column)
# -----------------------------
final_df.to_csv(
    os.path.join(base_folder, "malicious_domain_full.csv"),
    index=False
)

# -----------------------------
# Save ML-ready Dataset (without domain)
# -----------------------------
ml_ready_df = final_df.drop(columns=['domain']).copy()
ml_ready_df.to_csv(
    os.path.join(base_folder, "malicious_domain_ml_ready.csv"),
    index=False
)

# -----------------------------
# Save Train Dataset
# -----------------------------
train_df = X_train.copy()
train_df['label'] = y_train.values
train_df.to_csv(
    os.path.join(base_folder, "train_dataset.csv"),
    index=False
)

# -----------------------------
# Save Test Dataset
# -----------------------------
test_df = X_test.copy()
test_df['label'] = y_test.values
test_df.to_csv(
    os.path.join(base_folder, "test_dataset.csv"),
    index=False
)

print("All datasets saved successfully inside DMML_MINI_PROJECT/Dataset ✅")

# ============================================
# SECTION 2: LOAD DATASET FROM GOOGLE DRIVE
# Folder: MyDrive/DMML_MINI_PROJECT/dataset
# ============================================

from google.colab import drive
import pandas as pd
import os

# Step 1: Mount Google Drive
drive.mount('/content/drive')

# Step 2: Define folder path
base_folder = "/content/drive/MyDrive/DMML_MINI_PROJECT/Dataset1"

# Step 3: Define file paths
full_path = os.path.join(base_folder, "malicious_domain_full.csv")
ml_ready_path = os.path.join(base_folder, "malicious_domain_ml_ready.csv")
train_path = os.path.join(base_folder, "train_dataset.csv")
test_path = os.path.join(base_folder, "test_dataset.csv")

# Step 4: Load datasets
final_df = pd.read_csv(full_path)
ml_ready_df = pd.read_csv(ml_ready_path)
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

# Step 5: Display shapes
print("Datasets loaded successfully ✅")
print("Full dataset shape:", final_df.shape)
print("ML-ready dataset shape:", ml_ready_df.shape)
print("Train dataset shape:", train_df.shape)
print("Test dataset shape:", test_df.shape)
# ============================================
# SAVE SEPARATED TRAIN/TEST FEATURES & LABELS
# ============================================



# Save X_train
X_train.to_csv(os.path.join(base_folder, "X_train.csv"), index=False)

# Save y_train
y_train.to_csv(os.path.join(base_folder, "y_train.csv"), index=False)

# Save X_test
X_test.to_csv(os.path.join(base_folder, "X_test.csv"), index=False)

# Save y_test
y_test.to_csv(os.path.join(base_folder, "y_test.csv"), index=False)

print("X_train, y_train, X_test, y_test saved successfully ✅")

"""**XGBOOST**"""

from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score

xgb = XGBClassifier(
    n_estimators=600,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    scale_pos_weight=1,
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:,1]

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_xgb))
print("\nClassification Report:\n", classification_report(y_test, y_pred_xgb))

import numpy as np

for t in [0.5, 0.45, 0.4, 0.35]:
    y_adj = (y_prob_xgb > t).astype(int)
    print(f"\nThreshold = {t}")
    print(classification_report(y_test, y_adj))

!pip install catboost

# ============================================
# IMPORTS
# ============================================

import os
import joblib
import numpy as np

from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report, confusion_matrix

# ============================================
# PATH SETUP
# ============================================

save_path = "/content/drive/MyDrive/DMML_PROJECT"
os.makedirs(save_path, exist_ok=True)

model_path = f"{save_path}/cat_model_final.cbm" # Changed extension to .cbm


# ============================================
# COMPUTE CLASS IMBALANCE
# ============================================

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
scale_pos_weight = neg / pos

print("Scale_pos_weight:", scale_pos_weight)


# ============================================
# LOAD OR TRAIN MODEL (FORCING RETRAIN FOR NOW)
# ============================================

# Temporarily force retraining by setting this condition to False or commenting out the if-else
# To load a model if it exists, change `if False:` back to `if os.path.exists(model_path):`
if False: # os.path.exists(model_path):
    print("Loading saved CatBoost 🚀")
    cat_model = CatBoostClassifier(verbose=False) # Initialize with verbose=False for loading
    cat_model.load_model(model_path)

else:
    print("Training optimized CatBoost 🔥")

    cat_model = CatBoostClassifier(
        iterations=500,
        learning_rate=0.05,
        depth=6,
        l2_leaf_reg=3,

        # 🔥 IMPORTANT
        scale_pos_weight=scale_pos_weight,

        subsample=0.8,
        colsample_bylevel=0.8,

        loss_function='Logloss',
        eval_metric='AUC',

        random_seed=42,
        verbose=100
    )

    cat_model.fit(X_train, y_train)

    # SAVE MODEL
    cat_model.save_model(model_path) # Changed to native save_model method
    print("CatBoost saved ✅")


# ============================================
# PREDICTION
# ============================================

y_prob = cat_model.predict_proba(X_test)[:, 1]


# ============================================
# 🔥 BALANCED THRESHOLD TUNING (F1)
# ============================================

from sklearn.metrics import f1_score

best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.3, 0.7, 0.01):
    y_pred_temp = (y_prob >= t).astype(int)
    f1 = f1_score(y_test, y_pred_temp)

    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print("\n🔥 Best Threshold:", best_thresh)
print("🔥 Best F1 Score:", best_f1)


# ============================================
# FINAL RESULTS
# ============================================

y_pred = (y_prob >= best_thresh).astype(int)

print("\n===== FINAL CATBOOST RESULTS === RAM")

print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

"""MLP"""

import os
import numpy as np
import pandas as pd
import joblib

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, roc_auc_score

from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.regularizers import l2


# =========================
# CLEAN DATA
# =========================
X_train = X_train.replace([np.inf, -np.inf], np.nan).fillna(0)
X_test = X_test.replace([np.inf, -np.inf], np.nan).fillna(0)


# =========================
# LOAD OR CREATE SCALER
# =========================
if os.path.exists("url_scaler.pkl"):
    scaler = joblib.load("url_scaler.pkl")
else:
    scaler = StandardScaler()
    scaler.fit(X_train)
    joblib.dump(scaler, "url_scaler.pkl")

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


# =========================
# LOAD MODEL IF EXISTS
# =========================
if os.path.exists("advanced_url_model.h5"):

    print("Loading existing advanced model...")
    model = load_model("advanced_url_model.h5", compile=False)

else:

    print("Building new advanced model...")

    model = Sequential([

        Dense(512, activation='gelu',
              kernel_regularizer=l2(1e-4),
              input_shape=(X_train.shape[1],)),
        BatchNormalization(),
        Dropout(0.4),

        Dense(512, activation='gelu', kernel_regularizer=l2(1e-4)),
        BatchNormalization(),
        Dropout(0.35),

        Dense(256, activation='gelu', kernel_regularizer=l2(1e-4)),
        BatchNormalization(),
        Dropout(0.3),

        Dense(128, activation='gelu', kernel_regularizer=l2(1e-4)),
        BatchNormalization(),
        Dropout(0.25),

        Dense(64, activation='gelu'),
        Dropout(0.2),

        Dense(1, activation='sigmoid')
    ])


# =========================
# COMPILE MODEL
# =========================
model.compile(
    optimizer=Adam(
        learning_rate=0.0001,
        clipnorm=1.0
    ),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


# =========================
# CALLBACKS
# =========================
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=8,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.4,
    patience=4,
    min_lr=.0001
)


# =========================
# TRAIN MODEL
# =========================
history = model.fit(
    X_train_scaled,
    y_train,
    epochs=60,
    batch_size=32,
    validation_split=0.2,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)


# =========================
# EVALUATION
# =========================
y_prob = model.predict(X_test_scaled).ravel()
y_pred = (y_prob >= 0.5).astype(int)

print("\nEvaluation")
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))


# =========================
# SAVE MODEL
# =========================
model.save("advanced_url_model.h5")

print("\nAdvanced model saved.")

import pandas as pd
import matplotlib.pyplot as plt

y_prob = model.predict(X_test_scaled).ravel()
y_pred = (y_prob >= 0.5).astype(int)

print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print(classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\n")
importance = pd.Series(xgb.feature_importances_, index=X_train.columns)
importance = importance.sort_values(ascending=False)

print(importance.head(15))

plt.figure(figsize=(8,6))
importance.head(15).plot(kind='barh')
plt.gca().invert_yaxis()
plt.title("Top 15 Feature Importances (XGBoost)")
plt.show()

"""**STACKING**"""

import numpy as np
import joblib
import os
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, accuracy_score, roc_auc_score, classification_report, confusion_matrix
from tensorflow.keras.models import load_model # For MLP model
from sklearn.preprocessing import StandardScaler # For scaler
from sklearn.model_selection import GridSearchCV # Import GridSearchCV
from xgboost import XGBClassifier # Import XGBoost for meta-learner

# Define the path to saved models and scaler
save_path = "/content/drive/MyDrive/DMML_PROJECT"

# Load models
# FIX: Use the 'model' object directly from the kernel, which is the MLP trained on 33 features.
mlp_model = model # Use the in-memory MLP model
# FIX: Use the xgb and cat_model objects already in memory, trained on 33 features
xgb_model = xgb # Use the XGBoost model from kernel memory
cat_model = cat_model # Use the CatBoost model from kernel memory

# Load scaler - FIX: Load the correct scaler (url_scaler.pkl) that was fitted on 33 features.
scaler = joblib.load("url_scaler.pkl")

# Prepare data (X_test, y_test are assumed to be defined by previous train-test split)
X_test_clean = np.nan_to_num(X_test, nan=0.0, posinf=0.0, neginf=0.0)
X_test_mlp = scaler.transform(X_test_clean)
X_test_tree = X_test_clean.copy()

print("All models and data prepared ✅")

# ============================================
# GET PROBABILITIES FROM BASE MODELS
# ============================================

y_prob_mlp = mlp_model.predict(X_test_mlp, verbose=0).ravel()
y_prob_xgb = xgb_model.predict_proba(X_test_tree)[:, 1]
y_prob_cat = cat_model.predict_proba(X_test_tree)[:, 1]


# ============================================
# CREATE META FEATURES
# ============================================

meta_X = np.vstack((y_prob_xgb, y_prob_mlp, y_prob_cat)).T

print("Meta feature shape:", meta_X.shape)


# ============================================
# TUNE AND TRAIN META MODEL (STACKING) WITH XGBOOST
# ============================================

# Define the parameter grid for XGBoost meta-learner
param_grid_xgb = {
    'n_estimators': [50, 75, 100, 125, 150],
    'learning_rate': [0.05, 0.1, 0.15],
    'max_depth': [3, 4, 5],
    'subsample': [0.6, 0.7, 0.8],
    'colsample_bytree': [0.6, 0.7, 0.8]
}

# Initialize GridSearchCV for XGBoost meta-learner
grid_search = GridSearchCV(
    XGBClassifier(random_state=42, eval_metric='logloss'),
    param_grid_xgb,
    cv=5,
    scoring='f1',
    n_jobs=-1,
    verbose=1
)

print("Starting GridSearchCV for meta-model tuning (using XGBoost)...")
grid_search.fit(meta_X, y_test)

print(f"Best parameters found: {grid_search.best_params_}")
print(f"Best F1 score from GridSearchCV: {grid_search.best_score_:.4f}")

# Assign the best estimator found by GridSearchCV as the stacking_model
meta_model = grid_search.best_estimator_
stacking_model = meta_model # For consistency with adversarial test


# ============================================
# PREDICT USING META MODEL
# ============================================

final_prob = meta_model.predict_proba(meta_X)[:, 1]


# ============================================
# 🔥 THRESHOLD TUNING (F1 OPTIMIZED)
# ============================================

best_f1 = 0
best_thresh = 0.5

for t in np.arange(0.4, 0.6, 0.0005): # Finer step for threshold tuning
    y_pred_temp = (final_prob >= t).astype(int)
    f1 = f1_score(y_test, y_pred_temp)

    if f1 > best_f1:
        best_f1 = f1
        best_thresh = t

print(f"\n🔥 Best Threshold: {best_thresh}")
print(f"🔥 Best F1: {best_f1}")


# ============================================
# FINAL RESULTS
# ============================================

y_pred = (final_prob >= best_thresh).astype(int)

print("\n===== FINAL STACKING RESULTS (TUNED) ====")

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"ROC-AUC: {roc_auc_score(y_test, final_prob)}")

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

# ============================================
# SAVE STACKING MODEL AND THRESHOLD
# ============================================
stacking_model_path = os.path.join(save_path, "stacking_xgboost_meta_model.pkl")
joblib.dump(stacking_model, stacking_model_path)

threshold_data = {'best_threshold': best_thresh}
threshold_path = os.path.join(save_path, "stacking_xgboost_best_threshold.pkl")
joblib.dump(threshold_data, threshold_path)

print(f"\n✅ Stacked model saved to: {stacking_model_path}")
print(f"✅ Best threshold saved to: {threshold_path}")

"""**Create Model Comparison Table**"""

import pandas as pd

results = {
    "Model": [
        "XGBoost",
        "CatBoost",
        "Deep MLP",
        "Stacked model"
    ],
    "Accuracy": [
        0.9326, # Updated from cell N-9ovfahWt36
        0.9276, # Updated from cell ecYTAFMVw7qS (CatBoost final results accuracy)
        0.9381, # Updated from cell uu9pWvNl-e4p (MLP accuracy)
        0.9404  # Updated from LRzonXTGBOrD (non-OOF stacking accuracy)
    ],
    "ROC-AUC": [
        0.9785, # Updated from cell N-9ovfahWt36
        0.9764, # Updated from cell ecYTAFMVw7qS (CatBoost final results ROC-AUC)
        0.9816, # Updated from cell uu9pWvNl-e4p (MLP ROC-AUC)
        0.9831  # Updated from LRzonXTGBOrD (non-OOF stacking ROC-AUC)
    ],
    "Recall": [
        0.86,   # Updated from cell N-9ovfahWt36 (Malicious Recall)
        0.87,   # Updated from cell ecYTAFMVw7qS (CatBoost final results recall for class 1)
        0.87,   # Updated from cell uu9pWvNl-e4p (MLP recall for class 1)
        0.88    # Updated from LRzonXTGBOrD (non-OOF stacking recall for class 1)
    ],
    "F1 Score": [
        0.93,   # Updated from cell N-9ovfahWt36 (Weighted F1)
        0.93,   # Updated from cell ecYTAFMVw7qS (CatBoost final results weighted F1)
        0.94,   # Updated from cell uu9pWvNl-e4p (MLP weighted F1)
        0.94    # Updated from LRzonXTGBOrD (non-OOF stacking weighted F1)
    ]
}

df_results = pd.DataFrame(results)
df_results = df_results.round(4) # Rounding for cleaner display

# Add Rank based on ROC-AUC
df_results["Rank"] = df_results["ROC-AUC"].rank(ascending=False).astype(int)

# Sort by ROC-AUC for better comparison
df_results_sorted = df_results.sort_values(by="ROC-AUC", ascending=False).reset_index(drop=True)

# Filter for desired models (display all now that CNN is removed)
df_filtered = df_results_sorted.copy() # No need to filter if only selected models are present

print("Model Comparison Table (Filtered):")
display(df_filtered)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# --- FIX: Create fn_details DataFrame ---
# Assuming y_test and y_pred (from the stacking model) are available from previous cells
# Assuming final_df (with 'domain' and all features) is also available.
# We need to map X_test back to original features to get 'risk_score' for fn_details

# 1. Get the indices of false negatives
fn_indices = y_test[(y_test == 1) & (y_pred == 0)].index

# 2. Extract the corresponding rows from the original ML-ready DataFrame for these indices
# Note: ml_ready_df was created by dropping 'domain' column, but it contains all features.
# To get 'risk_score' and potentially other features for analysis, we use the X_test directly.
# Since ml_ready_df was built from final_df, we can reconstruct.

# Get the feature columns that were used for training (excluding 'label')
feature_cols = X_test.columns

# Create a DataFrame for false negatives using X_test and y_test
# Make sure to align the indices correctly if X_test was reset_index
# Assuming X_test and y_test maintain their original indices from ml_ready_df for slicing

fn_data = X_test.loc[fn_indices]
fn_data['label'] = y_test.loc[fn_indices]

# Now, fn_details contains the features of false negatives, including 'risk_score'
fn_details = fn_data

print(f"Found {len(fn_details)} False Negative samples.")

# --- Original plotting code ---
plt.figure(figsize=(8, 5))
sns.histplot(fn_details['risk_score'], bins=5, kde=True)
plt.title("Distribution of 'risk_score' for False Negatives")
plt.xlabel("Risk Score")
plt.ylabel("Number of False Negatives")

# Ensure max_risk_score is at least 0 to avoid range error if all risk_scores are negative or 0
max_risk_score = int(fn_details['risk_score'].max())
if max_risk_score < 0:
    max_risk_score = 0

plt.xticks(range(max_risk_score + 1))
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

print("\nDescriptive statistics for 'risk_score' in False Negatives:")
display(fn_details['risk_score'].describe())

print(f"Approximate number of False Negative samples analyzed: {len(fn_details)}\n")

print("--- Entropy analysis for False Negatives ---")
display(fn_details['entropy'].describe())

print("\n--- Domain Length analysis for False Negatives ---")
display(fn_details['domain_length'].describe())

print("\n--- Dot Count analysis for False Negatives ---")
display(fn_details['dot_count'].describe())

print("\n--- HTTPS presence analysis for False Negatives ---")
https_counts = fn_details['has_https'].value_counts(normalize=True) * 100
print(f"Percentage of FN samples with HTTPS: {https_counts.get(1, 0):.2f}%")
print(f"Percentage of FN samples without HTTPS: {https_counts.get(0, 0):.2f}%")

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, roc_auc_score

# --- Calculate ROC curve data for all models ---
# XGBoost
xgb_fpr, xgb_tpr, _ = roc_curve(y_test, y_prob_xgb)
xgb_auc = roc_auc_score(y_test, y_prob_xgb)

# CatBoost
cat_fpr, cat_tpr, _ = roc_curve(y_test, y_prob_cat)
cat_auc = roc_auc_score(y_test, y_prob_cat)

# MLP
mlp_fpr, mlp_tpr, _ = roc_curve(y_test, y_prob_mlp)
mlp_auc = roc_auc_score(y_test, y_prob_mlp)

# Stacked Model (using results from the non-OOF stacking cell LRzonXTGBOrD)
# final_prob is already available from LRzonXTGBOrD
stacked_fpr, stacked_tpr, _ = roc_curve(y_test, final_prob)
stacked_auc = roc_auc_score(y_test, final_prob)

# --- 1. SETUP CANVAS ---
plt.figure(figsize=(10, 8), facecolor='white')
ax = plt.gca()
ax.set_facecolor('white')

# --- DEBUG: Print cat_auc value ---
print(f"DEBUG: cat_auc = {cat_auc}")

# --- 2. PLOT BASE MODELS (Distinct Colors) ---
# Using specific Hex codes for maximum brightness on white
plt.plot(xgb_fpr, xgb_tpr, label=f"XGBoost (AUC = {xgb_auc:.5f})",
         color='#FF3366', lw=2) # Bright Rose/Pink

plt.plot(cat_fpr, cat_tpr, label=f"CatBoost (AUC = {cat_auc:.5f})",
         color='#FF9900', lw=2) # Deep Orange

plt.plot(mlp_fpr, mlp_tpr, label=f"MLP (AUC = {mlp_auc:.5f})",
         color='#33CC33', lw=2.5) # Leaf Green

# --- 3. THE "VISIBILITY TRICK" FOR STACKED MODEL ---
# We add + 0.003 to the TPR (y-axis) to force a physical gap
# so the green line (MLP) and blue line (Stacked) don't touch.
plt.plot(stacked_fpr, [y + 0.003 for y in stacked_tpr],
         label=f"Stacked Model (AUC = {stacked_auc:.5f})",
         color='#0066FF', # Pure Blue
         linewidth=4,
         linestyle='--',
         zorder=10) # Ensures it stays on top layer

# --- 4. FORMATTING & ZOOM ---
plt.plot([0,1], [0,1], color='black', linestyle=':', alpha=0.3)

# Extreme Zoom to show the separation clearly
plt.xlim([0.02, 0.08])
plt.ylim([0.84, 0.94])

plt.xlabel("False Positive Rate", fontweight='bold', fontsize=12)
plt.ylabel("True Positive Rate", fontweight='bold', fontsize=12)
plt.title("ROC Curve: Model 2 ", fontsize=14, pad=20)

# Legend with a shadow to make it stand out
plt.legend(loc="lower right", frameon=True, shadow=True, fontsize=10)
plt.grid(True, linestyle='--', alpha=0.5, color='gray')

plt.tight_layout()
plt.show()

"""### Detailed Explanation of Attack Types and Adversarial Results:

1.  **Encoding Obfuscation Attacks**:
    These techniques manipulate the way characters in a URL are represented to deceive detection systems, which might process the encoded URL differently than a human or an advanced parser.
    *   **Double URL Encoding**: Applies URL encoding twice (e.g., `%2520` for a space instead of `%20`). This can bypass naive decoders that only decode once.
    *   **Unicode Encoding**: Replaces ASCII characters with their Unicode escape sequences (e.g., `%u0061` for 'a'). This makes the URL appear benign or unrecognizable to systems not designed to handle specific Unicode representations.
    *   **Hex Encoding**: Converts parts of the domain (often the first segment) into hexadecimal representation (e.g., `0x7777772e` for `www.`). This is another form of obfuscation that can trick URL parsers or blacklisting mechanisms.

2.  **Homograph Attacks**:
    Homograph attacks exploit visual similarities between characters to create URLs that appear legitimate but lead to malicious sites. They rely on deceiving human users or systems that don't perform robust character normalization.
    *   **Homograph Attack (Character Replacement)**: Replaces characters with visually similar ones (e.g., 'i' with '1', 'o' with '0', 'a' with '@'). The goal is to make a malicious domain look like a trusted one at a glance.
    *   **Internationalized Domain Names (IDN)**: Uses characters from different alphabets (e.g., Cyrillic 'а' which looks like Latin 'a') or Punycode (`xn--`) to register domains that visually resemble legitimate brands, leading to spoofing.

3.  **Null Byte Injection Attack**:
    *   **Null Byte Injection**: Inserts a null byte (`%00`) into the URL, often within the domain or path. Some parsers will truncate the string at the null byte, effectively ignoring subsequent parts of the URL. This can be used to hide malicious segments or to make a URL appear to belong to a legitimate domain, e.g., `legit.com%00.badsite.com` might be interpreted as `legit.com` by a vulnerable system.

4.  **Adversarial Results (Metrics)**:
    Adversarial results refer to how well a model performs when subjected to deliberately crafted inputs (adversarial examples) designed to fool it. Key metrics for evaluating adversarial robustness include:
    *   **Attack Success Rate (ASR)**: This measures the percentage of malicious URLs that were successfully transformed by an attack technique (e.g., encoding, homograph) such that the model misclassifies them as benign. A high ASR indicates that the model is vulnerable to that particular attack type. The goal is to have a low ASR.
    *   **Accuracy Drop**: The difference between the model's accuracy on the original, untransformed test set and its accuracy on the adversarial test set. A significant drop indicates a lack of robustness.

These metrics help understand a model's weaknesses and guide further development to build more resilient detection systems against evolving threats.

### Model Performance Comparison
"""

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Assuming y_test and y_pred (from the stacking model) are available from previous cells
# y_pred was calculated in LRzonXTGBOrD using best_thresh

cm_stacked = confusion_matrix(y_test, y_pred)

# Create a ConfusionMatrixDisplay with custom labels and value format
disp_stacked = ConfusionMatrixDisplay(
    cm_stacked,
    display_labels=['Benign', 'Malicious']
)

fig, ax = plt.subplots(figsize=(7, 7)) # Increased figure size for better readability
disp_stacked.plot(cmap=plt.cm.Blues, ax=ax, values_format='d') # Added values_format='d' to display integers
ax.set_title("Confusion Matrix for Stacked Model", fontsize=14)
ax.set_xlabel("Predicted Label", fontsize=12)
ax.set_ylabel("True Label", fontsize=12)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

importance = pd.Series(xgb.feature_importances_, index=X_train.columns)
importance = importance.sort_values(ascending=False)

print(importance.head(20))

plt.figure(figsize=(8,6))

importance.head(15).plot(kind='barh')

plt.gca().invert_yaxis()
plt.xlabel("Importance Score")
plt.title("Top 15 Feature Importances (XGBoost)")

plt.show()

# Demonstrate the advanced attacks to verify the classes are working
demonstrate_advanced_attacks()

import numpy as np
import pandas as pd
from urllib.parse import quote, unquote, urlparse, parse_qs
import random
import string
import matplotlib.pyplot as plt
import seaborn as sns
import re


# ============================================
# ADVANCED ADVERSARIAL ATTACK STRATEGIES
# ============================================

class AdvancedAdversarialURLGenerator:
    """
    Advanced URL transformation techniques to test adversarial robustness.
    Based on known phishing and malware evasion tactics.
    """

    # EVASION TECHNIQUE 1: ENCODING OBFUSCATION
    @staticmethod
    def double_url_encoding(url):
        """Apply double URL encoding to bypass filters."""
        return quote(quote(url))

    @staticmethod
    def unicode_encoding(url):
        """Convert characters to unicode escape sequences."""
        if '://' in url:
            proto, rest = url.split('://', 1)
            # Apply unicode normalization
            encoded = ''.join(f'%u{ord(c):04x}' if ord(c) > 127 else c for c in rest)
            return f"{proto}://{encoded}"
        return url

    @staticmethod
    def hex_encoding(url):
        """Encode domain as hexadecimal."""
        if '://' in url:
            proto, rest = url.split('://', 1)
            if '/' in rest:
                domain, path = rest.split('/', 1)
                hex_domain = '0x' + ''.join(f'{ord(c):02x}' for c in domain.split('.')[0])
                return f"{proto}://{hex_domain}.{'.'.join(domain.split('.')[1:])}/{path}"
        return url

    # EVASION TECHNIQUE 2: IP-BASED OBFUSCATION
    @staticmethod
    def convert_to_ip_decimal(url):
        """Convert domain IP to decimal notation (if IP present)."""
        ip_pattern = r'\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b'

        match = re.search(ip_pattern, url)
        if match:
            ip = match.group()
            octets = [int(x) for x in ip.split('.')]
            decimal_ip = octets[0] * 256**3 + octets[1] * 256**2 + octets[2] * 256 + octets[3]
            return url.replace(ip, str(decimal_ip))
        return url

    @staticmethod
    def convert_to_ip_octal(url):
        """Convert domain IP to octal notation."""
        ip_pattern = r'\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b'

        match = re.search(ip_pattern, url)
        if match:
            ip = match.group()
            octets = [int(x) for x in ip.split('.')]
            octal_ip = '.'.join(oct(o)[2:] for o in octets)
            return url.replace(ip, octal_ip)
        return url

    # EVASION TECHNIQUE 3: DOMAIN MANIPULATION
    @staticmethod
    def add_null_byte(url):
        """Inject null bytes to confuse parsers."""
        if '://' in url:
            proto, rest = url.split('://', 1)
            # Insert null byte after domain
            if '/' in rest:
                domain, path = rest.split('/', 1)
                return f"{proto}://{domain}%00.good-domain.com/{path}"
        return url

    @staticmethod
    def add_user_info(url):
        """Add fake user:password to domain."""
        if '://' in url:
            proto, rest = url.split('://', 1)
            return f"{proto}://user:pass@{rest}"
        return url

    @staticmethod
    def use_shortener_like_pattern(url):
        """Mimic URL shortener patterns."""
        random_id = ''.join(random.choices(string.ascii_letters + string.digits, k=6))
        return f"https://tinyurl.com/{random_id}"

    # EVASION TECHNIQUE 4: QUERY PARAMETER OBFUSCATION
    @staticmethod
    def add_chaff_parameters(url):
        """Add irrelevant parameters to obscure real ones."""
        params = [
            'utm_source=google',
            'utm_medium=search',
            'utm_campaign=spring',
            'fbclid=1234567890',
            'gclid=0.0.0.0',
            'msclkid=abcdef123456'
        ]
        separator = '&' if '?' in url else '?'
        return url + separator + '&'.join(random.sample(params, k=2))

    @staticmethod
    def fragment_obfuscation(url):
        """Add fragment to hide suspicious parts from logs."""
        return f"{url}#legitimate-looking"

    # EVASION TECHNIQUE 5: HOMOGRAPH ATTACKS
    @staticmethod
    def homograph_attack(url):
        """Replace characters with lookalikes (i→1, o→0, etc)."""
        replacements = {
            'i': '1',
            'o': '0',
            'a': '@',
            's': '5',
            'e': '3',
            'b': '8'
        }

        if '://' in url:
            proto, rest = url.split('://', 1)
            if '/' in rest:
                domain, path = rest.split('/', 1)
                # Replace in domain
                domain = ''.join(replacements.get(c, c) for c in domain)
                return f"{proto}://{domain}/{path}"
        return url

    @staticmethod
    def internationalized_domain(url):
        """Use internationalized domain names (IDN) for spoofing."""
        if '://' in url:
            proto, rest = url.split('://', 1)
            if '/' in rest:
                domain, path = rest.split('/', 1)
                # Replace with punycode-like appearance
                return f"{proto}://xn--{domain.replace('.', '--')}.{path.split('/')[0] if path else 'com'}"
        return url

    # EVASION TECHNIQUE 6: SEMANTIC ATTACKS
    @staticmethod
    def case_manipulation(url):
        """Use mixed case to evade case-sensitive filters."""
        result = ""
        for char in url:
            if char.isalpha():
                result += char.upper() if random.random() > 0.5 else char.lower()
            else:
                result += char
        return result

    @staticmethod
    def whitespace_injection(url):
        """Inject whitespace that some parsers ignore."""
        return url.replace('//', '/ /')

    # COMPREHENSIVE ATTACK BATCH
    @staticmethod
    def generate_advanced_attacks(original_url, intensity='medium'):
        """
        Generate comprehensive attack variants.

        Args:
            original_url: Original URL
            intensity: 'low' (3 attacks), 'medium' (7), 'high' (all)

        Returns:
            List of (adversarial_url, attack_method, difficulty) tuples
        """
        all_attacks = [
            (AdvancedAdversarialURLGenerator.double_url_encoding, 'double_url_encoding', 'low'),
            (AdvancedAdversarialURLGenerator.hex_encoding, 'hex_encoding', 'medium'),
            (AdvancedAdversarialURLGenerator.add_null_byte, 'null_byte_injection', 'high'),
            (AdvancedAdversarialURLGenerator.add_user_info, 'user_info_obfuscation', 'medium'),
            (AdvancedAdversarialURLGenerator.add_chaff_parameters, 'chaff_parameters', 'low'),
            (AdvancedAdversarialURLGenerator.fragment_obfuscation, 'fragment_obfuscation', 'low'),
            (AdvancedAdversarialURLGenerator.homograph_attack, 'homograph_attack', 'medium'),
            (AdvancedAdversarialURLGenerator.case_manipulation, 'case_manipulation', 'low'),
            (AdvancedAdversarialURLGenerator.add_chaff_parameters, 'parameter_pollution', 'low'),
        ]

        if intensity == 'low':
            attacks_to_use = all_attacks[:3]
        elif intensity == 'medium':
            attacks_to_use = all_attacks[:7]
        else:  # high
            attacks_to_use = all_attacks

        results = [(original_url, 'original', 'baseline')]

        for attack_func, attack_name, difficulty in attacks_to_use:
            try:
                attacked_url = attack_func(original_url)
                results.append((attacked_url, attack_name, difficulty))
            except:
                # Catching exceptions during attack generation to continue process
                pass

        return results


# ============================================
# DETAILED ENSEMBLE ANALYSIS
# ============================================

class EnsembleAnalyzer:
    """
    Detailed analysis of ensemble model behavior and agreement patterns.
    """

    def __init__(self, detector):
        self.detector = detector

    def model_disagreement_analysis(self, X_features, y_true):
        """
        Analyze instances where models disagree.

        Returns:
            DataFrame with disagreement instances
        """
        predictions = {
            'xgb': None,
            'cat': None,
            'mlp': None,
            'ensemble': None
        }

        if self.detector.xgb_model:
            predictions['xgb'] = self.detector.xgb_model.predict(X_features)

        if self.detector.cat_model:
            predictions['cat'] = self.detector.cat_model.predict(X_features)

        if self.detector.mlp_model:
            # Assuming the MLP model uses scaled features
            X_scaled = self.detector.scaler.transform(X_features)
            predictions['mlp'] = (self.detector.mlp_model.predict(X_scaled, verbose=0).flatten() > 0.5).astype(int)

        ensemble_proba, ensemble_pred, _ = self.detector.predict(X_features)
        predictions['ensemble'] = ensemble_pred

        # Find disagreements
        disagreements = []
        for i in range(len(X_features)):
            preds = [predictions[k][i] for k in predictions if predictions[k] is not None]
            if len(set(preds)) > 1:  # Not all predictions agree
                disagreements.append({
                    'index': i,
                    'ensemble_pred': predictions['ensemble'][i],
                    'ensemble_proba': ensemble_proba[i],
                    'true_label': y_true[i],
                    'xgb': predictions['xgb'][i] if predictions['xgb'] is not None else None,
                    'cat': predictions['cat'][i] if predictions['cat'] is not None else None,
                    'mlp': predictions['mlp'][i] if predictions['mlp'] is not None else None,
                })

        return pd.DataFrame(disagreements)

    def confidence_analysis(self, X_features, y_true):
        """
        Analyze model confidence distributions.
        """
        probas = []

        if self.detector.xgb_model:
            xgb_proba = self.detector.xgb_model.predict_proba(X_features)[:, 1]
            probas.append(('XGBoost', xgb_proba))

        if self.detector.cat_model:
            cat_proba = self.detector.cat_model.predict_proba(X_features)[:, 1]
            probas.append(('CatBoost', cat_proba))

        if self.detector.mlp_model:
            # Assuming the MLP model uses scaled features
            X_scaled = self.detector.scaler.transform(X_features)
            mlp_proba = self.detector.mlp_model.predict(X_scaled, verbose=0).flatten()
            probas.append(('MLP', mlp_proba))

        # Ensemble
        ensemble_proba, _, _ = self.detector.predict(X_features)
        probas.append(('Ensemble', ensemble_proba))

        return probas

    def adversarial_transferability(self, adversarial_urls_df, label_col='label', url_col='url'):
        """
        Check if adversarial examples transfer across models.

        Returns:
            Transferability statistics
        """
        # This requires feature engineering logic that is not part of this module definition.
        # Placeholder for how it would connect to a feature engineering function
        # from adversarial_url_detection_test import feature_engineering # Example import
        # X_features = feature_engineering(adversarial_urls_df[[url_col]])

        print("Adversarial transferability analysis requires external feature engineering logic.")
        print("Please ensure 'feature_engineering' function is available in the environment or defined.")
        return {}

    def plot_confidence_distributions(self, probas_list, save_path=None):
        """
        Visualize model confidence distributions.
        """
        fig, axes = plt.subplots(1, len(probas_list), figsize=(15, 4))

        if len(probas_list) == 1:
            axes = [axes]

        for ax, (model_name, probas) in zip(axes, probas_list):
            ax.hist(probas[probas < 0.5], bins=20, alpha=0.6, label='Benign (pred)', color='green')
            ax.hist(probas[probas >= 0.5], bins=20, alpha=0.6, label='Malicious (pred)', color='red')
            ax.set_xlabel('Prediction Probability', fontsize=11)
            ax.set_ylabel('Frequency', fontsize=11)
            ax.set_title(f'{model_name} Confidence Distribution', fontsize=12, fontweight='bold')
            ax.legend()
            ax.grid(axis='y', alpha=0.3)

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')

        plt.show()


# ============================================
# ATTACK DIFFICULTY & SUCCESS METRICS
# ============================================

class AdversarialMetrics:
    """
    Compute advanced adversarial robustness metrics.
    """

    @staticmethod
    def compute_attack_success_rate(y_true, y_pred_original, y_pred_adversarial):
        """
        Compute attack success rate.

        Returns:
            Percentage of adversarial examples that successfully evade detection
        """
        successful_attacks = 0
        for i in range(len(y_true)):
            # Attack successful if: model correctly classifies original but misclassifies adversarial
            if y_pred_original[i] == y_true[i] and y_pred_adversarial[i] != y_true[i]:
                successful_attacks += 1

        return successful_attacks / len(y_true)

    @staticmethod
    def compute_robustness_score(results_by_difficulty):
        """
        Compute overall robustness score based on attack difficulty.

        Args:
            results_by_difficulty: Dict with keys 'low', 'medium', 'high'
                                  containing success rates

        Returns:
            Weighted robustness score (0-1, higher is better)
        """
        weights = {'low': 0.2, 'medium': 0.3, 'high': 0.5}
        score = 1.0  # Start at perfect

        for difficulty, weight in weights.items():
            if difficulty in results_by_difficulty:
                success_rate = results_by_difficulty[difficulty]
                score -= weight * success_rate

        return max(0, score)

    @staticmethod
    def compute_certified_robustness_radius(X_features, model_pred, epsilon=0.1):
        """
        Estimate certified robustness radius (feature space perturbation tolerance).

        Returns:
            Minimum distance to decision boundary for each sample
        """
        # This is a simplified version - real certified robustness uses more complex methods
        # For actual certified robustness, consider using randomized smoothing
        distances = np.abs(0.5 - model_pred)  # Distance to decision boundary at 0.5
        return distances


# ============================================
# EXAMPLE USAGE
# ============================================

def demonstrate_advanced_attacks():
    """
    Demonstrate advanced adversarial URL generation.
    """
    test_urls = [
        "https://secure-bank-login.tk/verify",
        "http://192.168.1.1/admin",
        "https://paypal.com/confirm"
    ]

    print("="*70)
    print("ADVANCED ADVERSARIAL ATTACK GENERATION")
    print("="*70)

    for url in test_urls:
        print("\nOriginal: " + url)
        print("-" * 70)

        attacks = AdvancedAdversarialURLGenerator.generate_advanced_attacks(
            url,
            intensity=random.choice(['low', 'medium', 'high'])
        )

        for adversarial, method, difficulty in attacks:
            print(f"[{difficulty.upper()}] {method:30} \u2192 {adversarial[:60]}...")

    print("\n" + "="*70)


# if __name__ == "__main__": # Commented out to prevent auto-execution on import
#     demonstrate_advanced_attacks()

# ============================================
# Feature Engineering Function for New URLs
# ============================================

def feature_engineer_urls(urls):
    # Create a DataFrame from the input URLs
    df_new = pd.DataFrame({'url': urls})

    # Step B: Extract Domain Safely (from COuFeJMYc3sW)
    def extract_domain_safe(url):
        try:
            parsed = urlparse(url)
            if not parsed.netloc:
                parsed = urlparse("http://" + url)
            domain = parsed.netloc
            if domain.startswith("www."):
                domain = domain[4:]
            return domain.lower()
        except Exception:
            return None

    df_new['domain'] = df_new['url'].apply(extract_domain_safe)

    # Remove invalid domains (important for feature creation)
    df_new = df_new.dropna(subset=['domain'])
    df_new = df_new[df_new['domain'].str.len() > 0].copy()

    # Initialize final_df for new features
    final_df_adversarial = df_new[['domain']].copy()

    # Apply basic lexical features (from N7GGD-pvRjWx)
    final_df_adversarial['domain_length'] = final_df_adversarial['domain'].apply(len)
    final_df_adversarial['dot_count'] = final_df_adversarial['domain'].apply(lambda x: x.count('.'))
    final_df_adversarial['hyphen_count'] = final_df_adversarial['domain'].apply(lambda x: x.count('-'))
    final_df_adversarial['digit_count'] = final_df_adversarial['domain'].apply(lambda x: sum(c.isdigit() for c in x))
    final_df_adversarial['digit_ratio'] = final_df_adversarial['digit_count'] / final_df_adversarial['domain_length'].replace(0, np.nan)
    final_df_adversarial['special_char_count'] = final_df_adversarial['domain'].apply(lambda x: len(re.findall(r'[^a-zA-Z0-9.-]', x)))
    final_df_adversarial['vowel_count'] = final_df_adversarial['domain'].apply(lambda x: sum(c in 'aeiou' for c in x))
    final_df_adversarial['vowel_ratio'] = final_df_adversarial['vowel_count'] / final_df_adversarial['domain_length'].replace(0, np.nan)
    final_df_adversarial['consonant_count'] = final_df_adversarial['domain'].apply(lambda x: sum(c.isalpha() and c not in 'aeiou' for c in x))
    final_df_adversarial = final_df_adversarial.fillna(0) # Fill NaN from division by zero

    final_df_adversarial['domain_uppercase_ratio'] = final_df_adversarial['domain'].apply(
        lambda x: sum(1 for c in x if c.isupper()) / len(x) if len(x) > 0 else 0
    )
    final_df_adversarial['longest_domain_token'] = final_df_adversarial['domain'].apply(
        lambda x: max((len(w) for w in x.split('.')), default=0)
    )

    # Entropy features
    def shannon_entropy(domain_or_url):
        prob = [float(domain_or_url.count(c)) / len(domain_or_url) for c in set(domain_or_url)]
        return -sum([p * math.log2(p) for p in prob])

    final_df_adversarial['entropy'] = final_df_adversarial['domain'].apply(shannon_entropy)
    final_df_adversarial['subdomain_entropy'] = final_df_adversarial['domain'].apply(
        lambda x: shannon_entropy(x.split('.')[0]) if x.split('.')[0] else 0
    )

    # URL Features - need to re-extract for each new URL, original df_new has 'url' column
    df_new['url_length'] = df_new['url'].apply(len)
    df_new['path'] = df_new['url'].apply(lambda x: urlparse(x).path)
    df_new['path_length'] = df_new['path'].apply(len)
    df_new['query'] = df_new['url'].apply(lambda x: urlparse(x).query)
    df_new['query_length'] = df_new['query'].apply(len)
    df_new['url_depth'] = df_new['path'].apply(lambda x: x.count('/'))
    df_new['param_count'] = df_new['query'].apply(lambda x: x.count('&') + 1 if x else 0)
    suspicious_ext = ['.exe','.zip','.rar','.js','.php','.scr','.bat']
    df_new['suspicious_extension'] = df_new['url'].apply(lambda x: 1 if any(x.lower().endswith(ext) for ext in suspicious_ext) else 0)
    df_new['encoded_char_count'] = df_new['url'].apply(lambda x: x.count('%'))
    df_new['encoding_density'] = df_new['url'].apply(lambda x: x.count('%') / len(x) if len(x) > 0 else 0)
    df_new['has_https'] = df_new['url'].apply(lambda x: 1 if x.startswith("https") else 0)
    df_new['token_count'] = df_new['url'].apply(lambda x: len(re.split(r'[./?=&-]', x)))
    keywords_path = ['login','admin','secure','update','account']
    df_new['path_keyword_flag'] = df_new['path'].apply(lambda x: 1 if any(k in x.lower() for k in keywords_path) else 0)
    df_new['url_entropy'] = df_new['url'].apply(shannon_entropy)
    df_new['url_digit_ratio'] = df_new['url'].apply(lambda x: sum(c.isdigit() for c in x) / len(x) if len(x) > 0 else 0)
    df_new['url_special_char_ratio'] = df_new['url'].apply(lambda x: sum(1 for c in x if not c.isalnum() and c not in ['/', '.', ':', '?','&', '=', '-']) / len(x) if len(x) > 0 else 0)
    df_new['url_vowel_ratio'] = df_new['url'].apply(lambda x: sum(1 for c in x.lower() if c in 'aeiou') / len(x) if len(x) > 0 else 0)
    df_new['url_consonant_ratio'] = df_new['url'].apply(lambda x: sum(1 for c in x.lower() if c.isalpha() and c not in 'aeiou') / len(x) if len(x) > 0 else 0)
    def has_port(url_str):
        parsed = urlparse(url_str)
        return 1 if parsed.port is not None else 0
    df_new['has_port'] = df_new['url'].apply(has_port)
    df_new['has_at_symbol'] = df_new['url'].apply(lambda x: 1 if '@' in x else 0)
    df_new['has_double_slash_in_path'] = df_new['path'].apply(lambda x: 1 if '//' in x else 0)

    url_features = [
        'url_length','path_length','query_length','url_depth',
        'param_count','suspicious_extension','encoded_char_count',
        'encoding_density','has_https','token_count','path_keyword_flag',
        'url_entropy', 'url_digit_ratio', 'url_special_char_ratio',
        'url_vowel_ratio', 'url_consonant_ratio', 'has_port',
        'has_at_symbol', 'has_double_slash_in_path'
    ]
    final_df_adversarial = pd.concat([final_df_adversarial.reset_index(drop=True), df_new[url_features].reset_index(drop=True)], axis=1)

    # CTI Features
    suspicious_tlds = ['xyz','tk','top','club','work','gq','cf','ml','ga']
    final_df_adversarial['suspicious_tld_flag'] = final_df_adversarial['domain'].apply(lambda x: 1 if x.split('.')[-1] in suspicious_tlds else 0)
    keywords = ['login','verify','secure','account','update','bank','paypal','signin','confirm']
    final_df_adversarial['suspicious_keyword_flag'] = df_new['url'].apply(lambda x: 1 if any(word in x.lower() for word in keywords) else 0)
    final_df_adversarial['length_anomaly'] = final_df_adversarial['domain_length'].apply(lambda x: 1 if x > 25 else 0)
    final_df_adversarial['contains_ip'] = final_df_adversarial['domain'].apply(lambda x: 1 if re.search(r'\d+\.\d+\.\d+\.\d+', x) else 0)
    brands = ['google','facebook','amazon','paypal','apple','microsoft']
    final_df_adversarial['brand_flag'] = df_new['url'].apply(lambda x: 1 if any(b in x.lower() for b in brands) else 0)
    def typo_score(domain):
        if not domain:
            return 0.0
        return max([SequenceMatcher(None, domain, b).ratio() for b in brands])
    final_df_adversarial['typosquat_score'] = final_df_adversarial['domain'].apply(typo_score)
    final_df_adversarial['risk_score'] = (
        final_df_adversarial['suspicious_tld_flag'] +
        final_df_adversarial['suspicious_keyword_flag'] +
        final_df_adversarial['length_anomaly'] +
        final_df_adversarial['contains_ip'] +
        final_df_adversarial['brand_flag']
    )

    # Pattern Features
    final_df_adversarial['unique_char_ratio'] = final_df_adversarial['domain'].apply(lambda x: len(set(x)) / len(x) if len(x) > 0 else 0)
    final_df_adversarial['max_repeated_char'] = final_df_adversarial['domain'].apply(lambda x: max([len(list(g)) for _, g in groupby(x)]) if len(x) > 0 else 0)

    # Sequence Features
    def longest_digit_seq(domain):
        max_seq = current = 0
        for c in domain:
            if c.isdigit():
                current += 1
                max_seq = max(max_seq, current)
            else:
                current = 0
        return max_seq
    final_df_adversarial['longest_digit_seq'] = final_df_adversarial['domain'].apply(longest_digit_seq)

    # Bigram Randomness
    def generate_bigrams(domain):
        return [domain[i:i+2] for i in range(len(domain)-1)]

    # Recalculate bigram_counts based on current adversarial domains if desired, or use global one.
    # For simplicity, we'll use a placeholder here or a pre-calculated global if available
    # For a proper calculation, this would need to be fit on the training data's domains.
    # For now, let's just make sure the column exists and has dummy data if bigram_counts not globally defined
    if 'bigram_counts' in globals():
        total_bigrams = sum(bigram_counts.values())
        def bigram_score(domain):
            bigrams = generate_bigrams(domain)
            score = 0
            if not bigrams or total_bigrams == 0:
                return 0.0
            for bg in bigrams:
                freq = bigram_counts.get(bg, 0.5) / total_bigrams
                score += -math.log2(freq) if freq > 0 else 0
            return score / len(bigrams) if bigrams else 0
        final_df_adversarial['bigram_randomness'] = final_df_adversarial['domain'].apply(bigram_score)
    else:
        # Placeholder if bigram_counts is not available, or re-run bigram setup from N7GGD-pvRjWx
        print("Warning: 'bigram_counts' not found. bigram_randomness will be set to 0. Please ensure bigram_counts is initialized from training data.")
        final_df_adversarial['bigram_randomness'] = 0.0

    # Ensure the order of columns matches X_train
    # Fill with 0 for any missing columns that might occur from new URLs not having certain features
    # or if some features couldn't be calculated for a given adversarial URL
    # X_train is a global variable from previous steps
    final_features_ordered = pd.DataFrame(columns=X_train.columns)
    final_features_adversarial = pd.concat([final_features_ordered, final_df_adversarial.drop(columns=['domain'], errors='ignore')], ignore_index=True)
    final_features_adversarial = final_features_adversarial.fillna(0)

    # Clean data (replace inf/-inf with NaN then fill NaN with 0)
    final_features_adversarial = final_features_adversarial.replace([np.inf, -np.inf], np.nan).fillna(0)

    return final_features_adversarial

# ============================================
# Generate Adversarial URLs
# ============================================

# Original URLs for generating adversarial examples
original_urls_to_attack = [
    "https://www.google.com/search?q=legit",
    "http://example.com/login.php",
    "https://amazon.com/gp/flex/sign-in",
    "http://bank-of-america.com/update_account.html",
    "https://malicious.xyz/download.exe", # Example malicious URL to see attack effect
    "https://phishing.tk/verify.html",
    "http://www.facebook.com/recover-account",
    "https://apple.com/billing-update",
    "http://secure.microsoft.com/password_reset",
    "https://docs.google.com/forms/d/e/legit",
    "http://badware.club/install.zip"
]

# Store generated adversarial URLs and their original intent (malicious/benign)
adversarial_data = []

# We'll use 'high' intensity attacks for maximum variants
for original_url in original_urls_to_attack:
    # Assign a 'true_label' to the original URL (0: benign, 1: malicious)
    true_label = 1 if ('login' in original_url or 'bank' in original_url or 'verify' in original_url or '.exe' in original_url or '.tk' in original_url or '.xyz' in original_url or 'facebook.com/recover' in original_url or 'apple.com/billing' in original_url or 'microsoft.com/password' in original_url or 'badware.club' in original_url) else 0

    attacks = AdvancedAdversarialURLGenerator.generate_advanced_attacks(
        original_url,
        intensity='high'
    )
    for adv_url, method, difficulty in attacks:
        adversarial_data.append({
            'original_url': original_url,
            'adversarial_url': adv_url,
            'attack_method': method,
            'difficulty': difficulty,
            'true_label': true_label # Label from original URL
        })

adversarial_df = pd.DataFrame(adversarial_data)

print(f"Generated {len(adversarial_df)} adversarial URLs.")
print("Sample adversarial URLs:")
display(adversarial_df.head())

# ============================================
# Feature Engineering Adversarial URLs
# ============================================

# Extract features for all generated adversarial URLs
X_adversarial = feature_engineer_urls(adversarial_df['adversarial_url'].tolist())

# Align columns with X_train - This step is crucial to ensure consistent feature sets
# If X_adversarial has columns not in X_train, they are dropped.
# If X_train has columns not in X_adversarial, they are added and filled with 0.
missing_cols = set(X_train.columns) - set(X_adversarial.columns)
for c in missing_cols:
    X_adversarial[c] = 0
X_adversarial = X_adversarial[X_train.columns]

# Separate labels if they were added during feature engineering
y_adversarial = adversarial_df['true_label']

print(f"Adversarial features shape: {X_adversarial.shape}")
display(X_adversarial.head())

# ============================================
# Model Predictions on Adversarial URLs
# ============================================

# Assuming models (xgb, cat_model, model (MLP), stacking_model) are already loaded in memory
# And scaler is also loaded

# Prepare features for MLP (scaled)
X_adversarial_mlp_scaled = scaler.transform(X_adversarial)

# Get predictions from individual models
y_pred_xgb_adv = xgb.predict(X_adversarial)
y_prob_xgb_adv = xgb.predict_proba(X_adversarial)[:, 1]

y_pred_cat_adv = cat_model.predict(X_adversarial)
y_prob_cat_adv = cat_model.predict_proba(X_adversarial)[:, 1]

y_pred_mlp_adv = (model.predict(X_adversarial_mlp_scaled, verbose=0).flatten() >= 0.5).astype(int)
y_prob_mlp_adv = model.predict(X_adversarial_mlp_scaled, verbose=0).flatten()

# Create meta-features for the stacked model
meta_X_adversarial = np.vstack((y_prob_xgb_adv, y_prob_mlp_adv, y_prob_cat_adv)).T

# Get stacked model predictions
# We need the best_thresh from the stacking model tuning (LRzonXTGBOrD)
# Assuming best_thresh is available from previous execution
if 'best_thresh' not in globals():
    print("Warning: 'best_thresh' for stacked model not found. Defaulting to 0.5.")
    best_thresh = 0.5

final_prob_adv = stacking_model.predict_proba(meta_X_adversarial)[:, 1]
y_pred_stacked_adv = (final_prob_adv >= best_thresh).astype(int)

# Add predictions back to adversarial_df for analysis
adversarial_df['pred_xgb'] = y_pred_xgb_adv
adversarial_df['pred_cat'] = y_pred_cat_adv
adversarial_df['pred_mlp'] = y_pred_mlp_adv
adversarial_df['pred_stacked'] = y_pred_stacked_adv

print("Predictions on adversarial URLs completed.")
display(adversarial_df.head(10))

# ============================================
# Evaluate Adversarial Robustness
# ============================================

print("\n--- Adversarial Robustness Evaluation ---")

# Calculate attack success rate for each model
def calculate_asr(y_true, y_pred_adv, model_name):
    misclassified_as_benign = np.sum((y_true == 1) & (y_pred_adv == 0))
    total_malicious_originals = np.sum(y_true == 1)
    if total_malicious_originals == 0:
        return 0 # No malicious URLs to attack
    asr = misclassified_as_benign / total_malicious_originals
    print(f"Attack Success Rate ({model_name}): {asr:.4f} (Misclassified malicious as benign)")
    return asr

# Filter for original malicious URLs to properly calculate ASR
malicious_adversarial_df = adversarial_df[adversarial_df['true_label'] == 1]

if not malicious_adversarial_df.empty:
    y_true_malicious = malicious_adversarial_df['true_label']
    calculate_asr(y_true_malicious, malicious_adversarial_df['pred_xgb'], 'XGBoost')
    calculate_asr(y_true_malicious, malicious_adversarial_df['pred_cat'], 'CatBoost')
    calculate_asr(y_true_malicious, malicious_adversarial_df['pred_mlp'], 'Deep MLP')
    calculate_asr(y_true_malicious, malicious_adversarial_df['pred_stacked'], 'Stacked Model')
else:
    print("No malicious URLs generated in the adversarial set to calculate Attack Success Rate.")

# Analyze overall accuracy on adversarial set
print("\n--- Overall Performance on Adversarial Set ---")
print(f"XGBoost Accuracy: {accuracy_score(y_adversarial, adversarial_df['pred_xgb']):.4f}")
print(f"CatBoost Accuracy: {accuracy_score(y_adversarial, adversarial_df['pred_cat']):.4f}")
print(f"Deep MLP Accuracy: {accuracy_score(y_adversarial, adversarial_df['pred_mlp']):.4f}")
print(f"Stacked Model Accuracy: {accuracy_score(y_adversarial, adversarial_df['pred_stacked']):.4f}")

# Further analysis using EnsembleAnalyzer (e.g., disagreement)
# Assuming 'detector' object (e.g., a wrapper around models) is available if EnsembleAnalyzer is to be used fully.
# For now, we can manually check disagreements among predictions.

adversarial_df['all_preds_agree'] = (
    (adversarial_df['pred_xgb'] == adversarial_df['pred_cat']) &
    (adversarial_df['pred_cat'] == adversarial_df['pred_mlp']) &
    (adversarial_df['pred_mlp'] == adversarial_df['pred_stacked'])
)

print(f"\nNumber of adversarial samples where all models agree: {adversarial_df['all_preds_agree'].sum()} out of {len(adversarial_df)}")
print(f"Number of adversarial samples where models disagree: {len(adversarial_df) - adversarial_df['all_preds_agree'].sum()}")

print("\nAdversarial robustness evaluation complete.")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Re-calculate ASR for clarity, assuming malicious_adversarial_df is still in memory
# Or, if not, re-run the relevant parts from bf5e31d4 or load from a stored variable.

# Filter for original malicious URLs to properly calculate ASR
malicious_adversarial_df = adversarial_df[adversarial_df['true_label'] == 1]

def calculate_asr_value(y_true, y_pred_adv):
    misclassified_as_benign = np.sum((y_true == 1) & (y_pred_adv == 0))
    total_malicious_originals = np.sum(y_true == 1)
    if total_malicious_originals == 0:
        return 0.0
    asr = misclassified_as_benign / total_malicious_originals
    return asr


if not malicious_adversarial_df.empty:
    y_true_malicious = malicious_adversarial_df['true_label']
    asr_xgb = calculate_asr_value(y_true_malicious, malicious_adversarial_df['pred_xgb'])
    asr_cat = calculate_asr_value(y_true_malicious, malicious_adversarial_df['pred_cat'])
    asr_mlp = calculate_asr_value(y_true_malicious, malicious_adversarial_df['pred_mlp'])
    asr_stacked = calculate_asr_value(y_true_malicious, malicious_adversarial_df['pred_stacked'])

    asr_data = {
        'Model': ['XGBoost', 'CatBoost', 'Deep MLP', 'Stacked Model'],
        'Attack Success Rate': [asr_xgb, asr_cat, asr_mlp, asr_stacked]
    }
    df_asr = pd.DataFrame(asr_data)

    plt.figure(figsize=(10, 6))
    sns.barplot(x='Model', y='Attack Success Rate', hue='Model', data=df_asr, palette='viridis', legend=False)
    plt.title('Attack Success Rate (Misclassified Malicious as Benign)', fontsize=14)
    plt.xlabel('Model', fontsize=12)
    plt.ylabel('ASR', fontsize=12)
    plt.ylim(0, df_asr['Attack Success Rate'].max() * 1.2) # Extend y-axis a bit for better visualization
    for index, row in df_asr.iterrows():
        plt.text(row.name, row['Attack Success Rate'] + 0.005, f'{row["Attack Success Rate"]:.4f}', color='black', ha="center")
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.show()
else:
    print("No malicious URLs found to plot Attack Success Rate.")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure df_comparison is available from previous steps
# If starting a new session, you might need to recreate it from previous steps,
# or load the pre-computed df_comparison if it was saved.

# Create a DataFrame for comparison if not already present from previous cells
# Assuming df_comparison was already created in cell 4f2798be

plt.figure(figsize=(10, 6))
sns.barplot(x='Model', y='Accuracy Drop', hue='Model', data=df_comparison, palette='viridis', legend=False)
plt.title('Accuracy Drop Across Models (Test Set vs. Adversarial Set)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy Drop', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Add text labels on top of bars
for index, row in df_comparison.iterrows():
    plt.text(row.name, row['Accuracy Drop'] + 0.005, f'{row["Accuracy Drop"]:.4f}', color='black', ha="center")

plt.tight_layout()
plt.show()

import pandas as pd

# --- Metrics for Original Test Set (from df_filtered) ---
# Using the df_filtered DataFrame created in cell dd9ecd2d
test_set_metrics = df_filtered.set_index('Model').copy()

# --- Metrics for Adversarial Set (from bf5e31d4 and 27dddd79 outputs) ---
adversarial_set_metrics_raw = {
    'XGBoost': {'Accuracy': 0.6636, 'ASR': 0.1250},
    'CatBoost': {'Accuracy': 0.6545, 'ASR': 0.1125},
    'Deep MLP': {'Accuracy': 0.5909, 'ASR': 0.2250},
    'Stacked model': {'Accuracy': 0.6545, 'ASR': 0.1375}
}
adversarial_set_metrics = pd.DataFrame.from_dict(adversarial_set_metrics_raw, orient='index')
adversarial_set_metrics.index.name = 'Model'

# Create a combined DataFrame for comparison
comparison_data = []

for model_name in test_set_metrics.index:
    test_acc = test_set_metrics.loc[model_name, 'Accuracy']
    test_roc_auc = test_set_metrics.loc[model_name, 'ROC-AUC']
    test_recall = test_set_metrics.loc[model_name, 'Recall']
    test_f1 = test_set_metrics.loc[model_name, 'F1 Score']

    adv_acc = adversarial_set_metrics.loc[model_name, 'Accuracy']
    adv_asr = adversarial_set_metrics.loc[model_name, 'ASR']

    comparison_data.append({
        'Model': model_name,
        'Test Set Accuracy': test_acc,
        'Test Set ROC-AUC': test_roc_auc,
        'Test Set Malicious Recall': test_recall, # Clarify this is for malicious class
        'Test Set Weighted F1': test_f1, # Clarify this is weighted F1
        'Adversarial Set Accuracy': adv_acc,
        'Adversarial Set ASR': adv_asr,
        'Accuracy Drop': test_acc - adv_acc
    })

df_comparison = pd.DataFrame(comparison_data)
df_comparison = df_comparison.round(4)

# Filter to include only the 'Stacked model'
df_comparison_filtered_stacked = df_comparison[df_comparison['Model'] == 'Stacked model'].copy()

print("\nModel Performance Comparison: Original Test Set vs. Adversarial Set (Stacked Model Only)")
display(df_comparison_filtered_stacked)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure df_comparison is available from previous steps

plt.figure(figsize=(10, 6))
sns.lineplot(x='Model', y='Accuracy Drop', data=df_comparison, marker='o', hue='Model', palette='viridis', legend=False)
plt.title('Accuracy Drop Across Models (Test Set vs. Adversarial Set)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy Drop', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(True, linestyle='--', alpha=0.7)

# Add text labels for each point
for index, row in df_comparison.iterrows():
    plt.text(row['Model'], row['Accuracy Drop'] + 0.005, f'{row["Accuracy Drop"]:.4f}', color='black', ha="center")

plt.tight_layout()
plt.show()

"""### Advanced Cyber Threat Intelligence (CTI) Features Used:

1.  **Suspicious TLD Flag (`suspicious_tld_flag`)**:
    *   **Definition**: A binary flag (1 or 0) indicating whether the domain's Top-Level Domain (TLD) is present in a predefined list of suspicious TLDs (e.g., `xyz`, `tk`, `top`, `club`, `work`, `gq`, `cf`, `ml`, `ga`). These TLDs are often abused by malicious actors.

2.  **Suspicious Keyword Flag (`suspicious_keyword_flag`)**:
    *   **Definition**: A binary flag (1 or 0) indicating if the URL contains any suspicious keywords commonly found in phishing or malicious links (e.g., `login`, `verify`, `secure`, `account`, `update`, `bank`, `paypal`, `signin`, `confirm`).

3.  **Length Anomaly (`length_anomaly`)**:
    *   **Definition**: A binary flag (1 or 0) set if the domain name's length exceeds a certain threshold (e.g., >25 characters). Very long domain names can sometimes be an indicator of malicious intent or an attempt to obscure the true nature of the URL.

4.  **Contains IP Address (`contains_ip`)**:
    *   **Definition**: A binary flag (1 or 0) indicating whether the domain part of the URL is an IP address instead of a traditional hostname. Malicious actors sometimes use IP addresses directly to host phishing pages or malware to bypass DNS-based filtering.

5.  **Brand Flag (`brand_flag`)**:
    *   **Definition**: A binary flag (1 or 0) indicating if the URL contains keywords resembling known brand names (e.g., `google`, `facebook`, `amazon`, `paypal`, `apple`, `microsoft`). This is a heuristic for potential brand impersonation in phishing attacks.

6.  **Typosquatting Score (`typosquat_score`)**:
    *   **Definition**: A score (0 to 1) representing the similarity of the domain to well-known brand names. A higher score suggests a higher likelihood of typosquatting, where attackers register domain names similar to legitimate ones to trick users.

7.  **Risk Score (`risk_score`)**:
    *   **Definition**: A combined heuristic score, calculated as the sum of `suspicious_tld_flag`, `suspicious_keyword_flag`, `length_anomaly`, `contains_ip`, and `brand_flag`. This aggregates several CTI-inspired indicators into a single value, providing an overall risk assessment based on these simple but effective checks.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure df_comparison is available

plt.figure(figsize=(10, 7))
sns.scatterplot(
    x='Adversarial Set ASR',
    y='Accuracy Drop',
    hue='Model',
    data=df_comparison,
    s=200, # Size of points
    palette='viridis',
    legend='full'
)

# Add text labels for each point
for i, row in df_comparison.iterrows():
    plt.text(row['Adversarial Set ASR'] + 0.005, row['Accuracy Drop'] + 0.005, row['Model'],
             fontsize=9, color='black', ha='left', va='bottom')

plt.title('Accuracy Drop vs. Adversarial Set ASR Across Models', fontsize=14)
plt.xlabel('Adversarial Set ASR', fontsize=12)
plt.ylabel('Accuracy Drop', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import pandas as pd

# Ensure df_comparison is available

correlation = df_comparison['Accuracy Drop'].corr(df_comparison['Adversarial Set ASR'])

print(f"Correlation between Accuracy Drop and Adversarial Set ASR: {correlation:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure df_comparison_filtered_stacked is available
# If starting a new session, you might need to recreate it from previous steps

plt.figure(figsize=(12, 6))

# Plot 1: Accuracy Drop for Stacked Model
plt.subplot(1, 2, 1) # 1 row, 2 columns, 1st plot
sns.barplot(x='Model', y='Accuracy Drop', hue='Model', data=df_comparison_filtered_stacked, palette='viridis', legend=False)
plt.title('Accuracy Drop (Stacked Model)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('Accuracy Drop', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Plot 2: Adversarial Set ASR for Stacked Model
plt.subplot(1, 2, 2) # 1 row, 2 columns, 2nd plot
sns.barplot(x='Model', y='Adversarial Set ASR', hue='Model', data=df_comparison_filtered_stacked, palette='magma', legend=False)
plt.title('Adversarial Set Attack Success Rate (Stacked Model)', fontsize=14)
plt.xlabel('Model', fontsize=12)
plt.ylabel('ASR', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()
